/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as auth_component from "../auth/component.js";
import type * as auth_functions_onCreateUser from "../auth/functions/onCreateUser.js";
import type * as auth_functions_onDeleteUser from "../auth/functions/onDeleteUser.js";
import type * as auth_functions_onUpdateUser from "../auth/functions/onUpdateUser.js";
import type * as auth_functions_purgeExpiredAuthData from "../auth/functions/purgeExpiredAuthData.js";
import type * as auth_internalMutations from "../auth/internalMutations.js";
import type * as blockShares_functions_blockShareMutations from "../blockShares/functions/blockShareMutations.js";
import type * as blockShares_functions_getBlockPermissionLevel from "../blockShares/functions/getBlockPermissionLevel.js";
import type * as blockShares_functions_getBlockSharesForBlock from "../blockShares/functions/getBlockSharesForBlock.js";
import type * as blockShares_functions_setBlocksShareStatus from "../blockShares/functions/setBlocksShareStatus.js";
import type * as blockShares_functions_shareBlocks from "../blockShares/functions/shareBlocks.js";
import type * as blockShares_functions_unshareBlocks from "../blockShares/functions/unshareBlocks.js";
import type * as blockShares_mutations from "../blockShares/mutations.js";
import type * as blockShares_queries from "../blockShares/queries.js";
import type * as blockShares_types from "../blockShares/types.js";
import type * as blocks_blockSchemas from "../blocks/blockSchemas.js";
import type * as blocks_functions_ensureBlocksPersisted from "../blocks/functions/ensureBlocksPersisted.js";
import type * as blocks_functions_extractPlainText from "../blocks/functions/extractPlainText.js";
import type * as blocks_functions_findBlockByBlockNoteId from "../blocks/functions/findBlockByBlockNoteId.js";
import type * as blocks_functions_flattenBlocks from "../blocks/functions/flattenBlocks.js";
import type * as blocks_functions_getAllBlocksByNote from "../blocks/functions/getAllBlocksByNote.js";
import type * as blocks_functions_getBlockWithShares from "../blocks/functions/getBlockWithShares.js";
import type * as blocks_functions_getBlocksWithShares from "../blocks/functions/getBlocksWithShares.js";
import type * as blocks_functions_getHeadingsByNote from "../blocks/functions/getHeadingsByNote.js";
import type * as blocks_functions_insertBlock from "../blocks/functions/insertBlock.js";
import type * as blocks_functions_reconstructBlockTree from "../blocks/functions/reconstructBlockTree.js";
import type * as blocks_functions_saveAllBlocksForNote from "../blocks/functions/saveAllBlocksForNote.js";
import type * as blocks_functions_searchBlocks from "../blocks/functions/searchBlocks.js";
import type * as blocks_functions_updateBlock from "../blocks/functions/updateBlock.js";
import type * as blocks_queries from "../blocks/queries.js";
import type * as blocks_types from "../blocks/types.js";
import type * as bookmarks_functions_getItemBookmark from "../bookmarks/functions/getItemBookmark.js";
import type * as bookmarks_functions_toggleItemBookmark from "../bookmarks/functions/toggleItemBookmark.js";
import type * as bookmarks_mutations from "../bookmarks/mutations.js";
import type * as bookmarks_types from "../bookmarks/types.js";
import type * as campaigns_constants from "../campaigns/constants.js";
import type * as campaigns_functions_createCampaign from "../campaigns/functions/createCampaign.js";
import type * as campaigns_functions_deleteCampaign from "../campaigns/functions/deleteCampaign.js";
import type * as campaigns_functions_getCampaign from "../campaigns/functions/getCampaign.js";
import type * as campaigns_functions_getCampaignMembers from "../campaigns/functions/getCampaignMembers.js";
import type * as campaigns_functions_getCampaignRequests from "../campaigns/functions/getCampaignRequests.js";
import type * as campaigns_functions_getUserCampaigns from "../campaigns/functions/getUserCampaigns.js";
import type * as campaigns_functions_joinCampaign from "../campaigns/functions/joinCampaign.js";
import type * as campaigns_functions_updateCampaign from "../campaigns/functions/updateCampaign.js";
import type * as campaigns_functions_updateCampaignMemberStatus from "../campaigns/functions/updateCampaignMemberStatus.js";
import type * as campaigns_mutations from "../campaigns/mutations.js";
import type * as campaigns_queries from "../campaigns/queries.js";
import type * as campaigns_types from "../campaigns/types.js";
import type * as campaigns_validation from "../campaigns/validation.js";
import type * as canvases_baseSchema from "../canvases/baseSchema.js";
import type * as canvases_functions_captureCanvasSnapshot from "../canvases/functions/captureCanvasSnapshot.js";
import type * as canvases_functions_createCanvas from "../canvases/functions/createCanvas.js";
import type * as canvases_functions_enhanceCanvas from "../canvases/functions/enhanceCanvas.js";
import type * as canvases_functions_rollbackCanvas from "../canvases/functions/rollbackCanvas.js";
import type * as canvases_functions_updateCanvas from "../canvases/functions/updateCanvas.js";
import type * as canvases_mutations from "../canvases/mutations.js";
import type * as canvases_triggers from "../canvases/triggers.js";
import type * as canvases_types from "../canvases/types.js";
import type * as common_constants from "../common/constants.js";
import type * as common_logger from "../common/logger.js";
import type * as common_slug from "../common/slug.js";
import type * as common_types from "../common/types.js";
import type * as crons from "../crons.js";
import type * as documentSnapshots_functions_createSnapshot from "../documentSnapshots/functions/createSnapshot.js";
import type * as documentSnapshots_functions_getSnapshot from "../documentSnapshots/functions/getSnapshot.js";
import type * as documentSnapshots_functions_rollbackToSnapshot from "../documentSnapshots/functions/rollbackToSnapshot.js";
import type * as documentSnapshots_mutations from "../documentSnapshots/mutations.js";
import type * as documentSnapshots_queries from "../documentSnapshots/queries.js";
import type * as documentSnapshots_types from "../documentSnapshots/types.js";
import type * as editHistory_log from "../editHistory/log.js";
import type * as editHistory_queries from "../editHistory/queries.js";
import type * as editHistory_types from "../editHistory/types.js";
import type * as editors_functions_getCurrentEditor from "../editors/functions/getCurrentEditor.js";
import type * as editors_functions_setCurrentEditor from "../editors/functions/setCurrentEditor.js";
import type * as editors_mutations from "../editors/mutations.js";
import type * as editors_queries from "../editors/queries.js";
import type * as editors_types from "../editors/types.js";
import type * as email from "../email.js";
import type * as errors from "../errors.js";
import type * as files_functions_createFile from "../files/functions/createFile.js";
import type * as files_functions_enhanceFile from "../files/functions/enhanceFile.js";
import type * as files_functions_updateFile from "../files/functions/updateFile.js";
import type * as files_mutations from "../files/mutations.js";
import type * as files_queries from "../files/queries.js";
import type * as files_triggers from "../files/triggers.js";
import type * as files_types from "../files/types.js";
import type * as folders_baseSchema from "../folders/baseSchema.js";
import type * as folders_functions_createFolder from "../folders/functions/createFolder.js";
import type * as folders_functions_enhanceFolder from "../folders/functions/enhanceFolder.js";
import type * as folders_functions_getFolderContentsForDownload from "../folders/functions/getFolderContentsForDownload.js";
import type * as folders_functions_getSidebarItemAncestors from "../folders/functions/getSidebarItemAncestors.js";
import type * as folders_functions_updateFolder from "../folders/functions/updateFolder.js";
import type * as folders_mutations from "../folders/mutations.js";
import type * as folders_queries from "../folders/queries.js";
import type * as folders_triggers from "../folders/triggers.js";
import type * as folders_types from "../folders/types.js";
import type * as functions from "../functions.js";
import type * as gameMaps_baseSchema from "../gameMaps/baseSchema.js";
import type * as gameMaps_functions_captureGameMapSnapshot from "../gameMaps/functions/captureGameMapSnapshot.js";
import type * as gameMaps_functions_createItemPin from "../gameMaps/functions/createItemPin.js";
import type * as gameMaps_functions_createMap from "../gameMaps/functions/createMap.js";
import type * as gameMaps_functions_enhanceMap from "../gameMaps/functions/enhanceMap.js";
import type * as gameMaps_functions_removeItemPin from "../gameMaps/functions/removeItemPin.js";
import type * as gameMaps_functions_requirePinAccess from "../gameMaps/functions/requirePinAccess.js";
import type * as gameMaps_functions_rollbackGameMap from "../gameMaps/functions/rollbackGameMap.js";
import type * as gameMaps_functions_updateItemPin from "../gameMaps/functions/updateItemPin.js";
import type * as gameMaps_functions_updateMap from "../gameMaps/functions/updateMap.js";
import type * as gameMaps_functions_updatePinVisibility from "../gameMaps/functions/updatePinVisibility.js";
import type * as gameMaps_mutations from "../gameMaps/mutations.js";
import type * as gameMaps_queries from "../gameMaps/queries.js";
import type * as gameMaps_triggers from "../gameMaps/triggers.js";
import type * as gameMaps_types from "../gameMaps/types.js";
import type * as gameMaps_validation from "../gameMaps/validation.js";
import type * as http from "../http.js";
import type * as links_functions_getBacklinksForItem from "../links/functions/getBacklinksForItem.js";
import type * as links_functions_getOutgoingLinksForNote from "../links/functions/getOutgoingLinksForNote.js";
import type * as links_functions_syncNoteLinks from "../links/functions/syncNoteLinks.js";
import type * as links_linkParsers from "../links/linkParsers.js";
import type * as links_linkResolution from "../links/linkResolution.js";
import type * as links_queries from "../links/queries.js";
import type * as links_types from "../links/types.js";
import type * as notes_blocknote from "../notes/blocknote.js";
import type * as notes_editorSpecs from "../notes/editorSpecs.js";
import type * as notes_functions_captureNoteSnapshot from "../notes/functions/captureNoteSnapshot.js";
import type * as notes_functions_createNote from "../notes/functions/createNote.js";
import type * as notes_functions_enhanceNote from "../notes/functions/enhanceNote.js";
import type * as notes_functions_rollbackNote from "../notes/functions/rollbackNote.js";
import type * as notes_functions_updateNote from "../notes/functions/updateNote.js";
import type * as notes_mutations from "../notes/mutations.js";
import type * as notes_queries from "../notes/queries.js";
import type * as notes_triggers from "../notes/triggers.js";
import type * as notes_types from "../notes/types.js";
import type * as permissions_hasAtLeastPermissionLevel from "../permissions/hasAtLeastPermissionLevel.js";
import type * as permissions_types from "../permissions/types.js";
import type * as sessions_functions_endCurrentSession from "../sessions/functions/endCurrentSession.js";
import type * as sessions_functions_getCurrentSession from "../sessions/functions/getCurrentSession.js";
import type * as sessions_functions_getSession from "../sessions/functions/getSession.js";
import type * as sessions_functions_getSessionsByCampaign from "../sessions/functions/getSessionsByCampaign.js";
import type * as sessions_functions_setCurrentSession from "../sessions/functions/setCurrentSession.js";
import type * as sessions_functions_startSession from "../sessions/functions/startSession.js";
import type * as sessions_functions_updateSession from "../sessions/functions/updateSession.js";
import type * as sessions_mutations from "../sessions/mutations.js";
import type * as sessions_queries from "../sessions/queries.js";
import type * as sessions_types from "../sessions/types.js";
import type * as sidebarItems_functions_claimPreviewGeneration from "../sidebarItems/functions/claimPreviewGeneration.js";
import type * as sidebarItems_functions_collectDescendants from "../sidebarItems/functions/collectDescendants.js";
import type * as sidebarItems_functions_defaultItemName from "../sidebarItems/functions/defaultItemName.js";
import type * as sidebarItems_functions_emptyTrashBin from "../sidebarItems/functions/emptyTrashBin.js";
import type * as sidebarItems_functions_enhanceSidebarItem from "../sidebarItems/functions/enhanceSidebarItem.js";
import type * as sidebarItems_functions_fetchCampaignSidebarItems from "../sidebarItems/functions/fetchCampaignSidebarItems.js";
import type * as sidebarItems_functions_getSidebarItem from "../sidebarItems/functions/getSidebarItem.js";
import type * as sidebarItems_functions_getSidebarItemBySlug from "../sidebarItems/functions/getSidebarItemBySlug.js";
import type * as sidebarItems_functions_getSidebarItemWithContent from "../sidebarItems/functions/getSidebarItemWithContent.js";
import type * as sidebarItems_functions_getSidebarItemsByParent from "../sidebarItems/functions/getSidebarItemsByParent.js";
import type * as sidebarItems_functions_hardDeleteItem from "../sidebarItems/functions/hardDeleteItem.js";
import type * as sidebarItems_functions_moveSidebarItem from "../sidebarItems/functions/moveSidebarItem.js";
import type * as sidebarItems_functions_permanentlyDeleteSidebarItem from "../sidebarItems/functions/permanentlyDeleteSidebarItem.js";
import type * as sidebarItems_functions_purgeExpiredTrash from "../sidebarItems/functions/purgeExpiredTrash.js";
import type * as sidebarItems_functions_setPreviewImage from "../sidebarItems/functions/setPreviewImage.js";
import type * as sidebarItems_functions_treeOperations from "../sidebarItems/functions/treeOperations.js";
import type * as sidebarItems_internalMutations from "../sidebarItems/internalMutations.js";
import type * as sidebarItems_mutations from "../sidebarItems/mutations.js";
import type * as sidebarItems_queries from "../sidebarItems/queries.js";
import type * as sidebarItems_schema_anySidebarItemValidator from "../sidebarItems/schema/anySidebarItemValidator.js";
import type * as sidebarItems_schema_anySidebarItemWithContentValidator from "../sidebarItems/schema/anySidebarItemWithContentValidator.js";
import type * as sidebarItems_schema_sidebarItemsTable from "../sidebarItems/schema/sidebarItemsTable.js";
import type * as sidebarItems_schema_validators from "../sidebarItems/schema/validators.js";
import type * as sidebarItems_sharedValidation from "../sidebarItems/sharedValidation.js";
import type * as sidebarItems_triggerTypes from "../sidebarItems/triggerTypes.js";
import type * as sidebarItems_triggers from "../sidebarItems/triggers.js";
import type * as sidebarItems_types_baseTypes from "../sidebarItems/types/baseTypes.js";
import type * as sidebarItems_types_types from "../sidebarItems/types/types.js";
import type * as sidebarItems_validation from "../sidebarItems/validation.js";
import type * as sidebarShares_functions_getSidebarItemShares from "../sidebarShares/functions/getSidebarItemShares.js";
import type * as sidebarShares_functions_getSidebarItemSharesForItem from "../sidebarShares/functions/getSidebarItemSharesForItem.js";
import type * as sidebarShares_functions_getSidebarItemWithShares from "../sidebarShares/functions/getSidebarItemWithShares.js";
import type * as sidebarShares_functions_setAllPlayersPermission from "../sidebarShares/functions/setAllPlayersPermission.js";
import type * as sidebarShares_functions_setFolderInheritShares from "../sidebarShares/functions/setFolderInheritShares.js";
import type * as sidebarShares_functions_shareSidebarItem from "../sidebarShares/functions/shareSidebarItem.js";
import type * as sidebarShares_functions_sidebarItemPermissions from "../sidebarShares/functions/sidebarItemPermissions.js";
import type * as sidebarShares_functions_sidebarItemShareMutations from "../sidebarShares/functions/sidebarItemShareMutations.js";
import type * as sidebarShares_functions_unshareSidebarItem from "../sidebarShares/functions/unshareSidebarItem.js";
import type * as sidebarShares_mutations from "../sidebarShares/mutations.js";
import type * as sidebarShares_queries from "../sidebarShares/queries.js";
import type * as sidebarShares_types from "../sidebarShares/types.js";
import type * as storage_functions_commitUpload from "../storage/functions/commitUpload.js";
import type * as storage_functions_getDownloadUrl from "../storage/functions/getDownloadUrl.js";
import type * as storage_functions_getStorageMetadata from "../storage/functions/getStorageMetadata.js";
import type * as storage_functions_trackUpload from "../storage/functions/trackUpload.js";
import type * as storage_mutations from "../storage/mutations.js";
import type * as storage_queries from "../storage/queries.js";
import type * as storage_types from "../storage/types.js";
import type * as storage_validation from "../storage/validation.js";
import type * as triggers from "../triggers.js";
import type * as userPreferences_mutations from "../userPreferences/mutations.js";
import type * as userPreferences_queries from "../userPreferences/queries.js";
import type * as userPreferences_types from "../userPreferences/types.js";
import type * as users_constants from "../users/constants.js";
import type * as users_functions_checkUsernameExists from "../users/functions/checkUsernameExists.js";
import type * as users_functions_getUserProfile from "../users/functions/getUserProfile.js";
import type * as users_mutations from "../users/mutations.js";
import type * as users_queries from "../users/queries.js";
import type * as users_types from "../users/types.js";
import type * as users_validation from "../users/validation.js";
import type * as yjsSync_constants from "../yjsSync/constants.js";
import type * as yjsSync_functions_captureYjsState from "../yjsSync/functions/captureYjsState.js";
import type * as yjsSync_functions_checkYjsAccess from "../yjsSync/functions/checkYjsAccess.js";
import type * as yjsSync_functions_compactUpdates from "../yjsSync/functions/compactUpdates.js";
import type * as yjsSync_functions_createYjsDocument from "../yjsSync/functions/createYjsDocument.js";
import type * as yjsSync_functions_deleteYjsDocument from "../yjsSync/functions/deleteYjsDocument.js";
import type * as yjsSync_functions_reconstructYDoc from "../yjsSync/functions/reconstructYDoc.js";
import type * as yjsSync_functions_rollbackYjsDocument from "../yjsSync/functions/rollbackYjsDocument.js";
import type * as yjsSync_functions_types from "../yjsSync/functions/types.js";
import type * as yjsSync_functions_uint8ToArrayBuffer from "../yjsSync/functions/uint8ToArrayBuffer.js";
import type * as yjsSync_internalMutations from "../yjsSync/internalMutations.js";
import type * as yjsSync_mutations from "../yjsSync/mutations.js";
import type * as yjsSync_queries from "../yjsSync/queries.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

declare const fullApi: ApiFromModules<{
  "auth/component": typeof auth_component;
  "auth/functions/onCreateUser": typeof auth_functions_onCreateUser;
  "auth/functions/onDeleteUser": typeof auth_functions_onDeleteUser;
  "auth/functions/onUpdateUser": typeof auth_functions_onUpdateUser;
  "auth/functions/purgeExpiredAuthData": typeof auth_functions_purgeExpiredAuthData;
  "auth/internalMutations": typeof auth_internalMutations;
  "blockShares/functions/blockShareMutations": typeof blockShares_functions_blockShareMutations;
  "blockShares/functions/getBlockPermissionLevel": typeof blockShares_functions_getBlockPermissionLevel;
  "blockShares/functions/getBlockSharesForBlock": typeof blockShares_functions_getBlockSharesForBlock;
  "blockShares/functions/setBlocksShareStatus": typeof blockShares_functions_setBlocksShareStatus;
  "blockShares/functions/shareBlocks": typeof blockShares_functions_shareBlocks;
  "blockShares/functions/unshareBlocks": typeof blockShares_functions_unshareBlocks;
  "blockShares/mutations": typeof blockShares_mutations;
  "blockShares/queries": typeof blockShares_queries;
  "blockShares/types": typeof blockShares_types;
  "blocks/blockSchemas": typeof blocks_blockSchemas;
  "blocks/functions/ensureBlocksPersisted": typeof blocks_functions_ensureBlocksPersisted;
  "blocks/functions/extractPlainText": typeof blocks_functions_extractPlainText;
  "blocks/functions/findBlockByBlockNoteId": typeof blocks_functions_findBlockByBlockNoteId;
  "blocks/functions/flattenBlocks": typeof blocks_functions_flattenBlocks;
  "blocks/functions/getAllBlocksByNote": typeof blocks_functions_getAllBlocksByNote;
  "blocks/functions/getBlockWithShares": typeof blocks_functions_getBlockWithShares;
  "blocks/functions/getBlocksWithShares": typeof blocks_functions_getBlocksWithShares;
  "blocks/functions/getHeadingsByNote": typeof blocks_functions_getHeadingsByNote;
  "blocks/functions/insertBlock": typeof blocks_functions_insertBlock;
  "blocks/functions/reconstructBlockTree": typeof blocks_functions_reconstructBlockTree;
  "blocks/functions/saveAllBlocksForNote": typeof blocks_functions_saveAllBlocksForNote;
  "blocks/functions/searchBlocks": typeof blocks_functions_searchBlocks;
  "blocks/functions/updateBlock": typeof blocks_functions_updateBlock;
  "blocks/queries": typeof blocks_queries;
  "blocks/types": typeof blocks_types;
  "bookmarks/functions/getItemBookmark": typeof bookmarks_functions_getItemBookmark;
  "bookmarks/functions/toggleItemBookmark": typeof bookmarks_functions_toggleItemBookmark;
  "bookmarks/mutations": typeof bookmarks_mutations;
  "bookmarks/types": typeof bookmarks_types;
  "campaigns/constants": typeof campaigns_constants;
  "campaigns/functions/createCampaign": typeof campaigns_functions_createCampaign;
  "campaigns/functions/deleteCampaign": typeof campaigns_functions_deleteCampaign;
  "campaigns/functions/getCampaign": typeof campaigns_functions_getCampaign;
  "campaigns/functions/getCampaignMembers": typeof campaigns_functions_getCampaignMembers;
  "campaigns/functions/getCampaignRequests": typeof campaigns_functions_getCampaignRequests;
  "campaigns/functions/getUserCampaigns": typeof campaigns_functions_getUserCampaigns;
  "campaigns/functions/joinCampaign": typeof campaigns_functions_joinCampaign;
  "campaigns/functions/updateCampaign": typeof campaigns_functions_updateCampaign;
  "campaigns/functions/updateCampaignMemberStatus": typeof campaigns_functions_updateCampaignMemberStatus;
  "campaigns/mutations": typeof campaigns_mutations;
  "campaigns/queries": typeof campaigns_queries;
  "campaigns/types": typeof campaigns_types;
  "campaigns/validation": typeof campaigns_validation;
  "canvases/baseSchema": typeof canvases_baseSchema;
  "canvases/functions/captureCanvasSnapshot": typeof canvases_functions_captureCanvasSnapshot;
  "canvases/functions/createCanvas": typeof canvases_functions_createCanvas;
  "canvases/functions/enhanceCanvas": typeof canvases_functions_enhanceCanvas;
  "canvases/functions/rollbackCanvas": typeof canvases_functions_rollbackCanvas;
  "canvases/functions/updateCanvas": typeof canvases_functions_updateCanvas;
  "canvases/mutations": typeof canvases_mutations;
  "canvases/triggers": typeof canvases_triggers;
  "canvases/types": typeof canvases_types;
  "common/constants": typeof common_constants;
  "common/logger": typeof common_logger;
  "common/slug": typeof common_slug;
  "common/types": typeof common_types;
  crons: typeof crons;
  "documentSnapshots/functions/createSnapshot": typeof documentSnapshots_functions_createSnapshot;
  "documentSnapshots/functions/getSnapshot": typeof documentSnapshots_functions_getSnapshot;
  "documentSnapshots/functions/rollbackToSnapshot": typeof documentSnapshots_functions_rollbackToSnapshot;
  "documentSnapshots/mutations": typeof documentSnapshots_mutations;
  "documentSnapshots/queries": typeof documentSnapshots_queries;
  "documentSnapshots/types": typeof documentSnapshots_types;
  "editHistory/log": typeof editHistory_log;
  "editHistory/queries": typeof editHistory_queries;
  "editHistory/types": typeof editHistory_types;
  "editors/functions/getCurrentEditor": typeof editors_functions_getCurrentEditor;
  "editors/functions/setCurrentEditor": typeof editors_functions_setCurrentEditor;
  "editors/mutations": typeof editors_mutations;
  "editors/queries": typeof editors_queries;
  "editors/types": typeof editors_types;
  email: typeof email;
  errors: typeof errors;
  "files/functions/createFile": typeof files_functions_createFile;
  "files/functions/enhanceFile": typeof files_functions_enhanceFile;
  "files/functions/updateFile": typeof files_functions_updateFile;
  "files/mutations": typeof files_mutations;
  "files/queries": typeof files_queries;
  "files/triggers": typeof files_triggers;
  "files/types": typeof files_types;
  "folders/baseSchema": typeof folders_baseSchema;
  "folders/functions/createFolder": typeof folders_functions_createFolder;
  "folders/functions/enhanceFolder": typeof folders_functions_enhanceFolder;
  "folders/functions/getFolderContentsForDownload": typeof folders_functions_getFolderContentsForDownload;
  "folders/functions/getSidebarItemAncestors": typeof folders_functions_getSidebarItemAncestors;
  "folders/functions/updateFolder": typeof folders_functions_updateFolder;
  "folders/mutations": typeof folders_mutations;
  "folders/queries": typeof folders_queries;
  "folders/triggers": typeof folders_triggers;
  "folders/types": typeof folders_types;
  functions: typeof functions;
  "gameMaps/baseSchema": typeof gameMaps_baseSchema;
  "gameMaps/functions/captureGameMapSnapshot": typeof gameMaps_functions_captureGameMapSnapshot;
  "gameMaps/functions/createItemPin": typeof gameMaps_functions_createItemPin;
  "gameMaps/functions/createMap": typeof gameMaps_functions_createMap;
  "gameMaps/functions/enhanceMap": typeof gameMaps_functions_enhanceMap;
  "gameMaps/functions/removeItemPin": typeof gameMaps_functions_removeItemPin;
  "gameMaps/functions/requirePinAccess": typeof gameMaps_functions_requirePinAccess;
  "gameMaps/functions/rollbackGameMap": typeof gameMaps_functions_rollbackGameMap;
  "gameMaps/functions/updateItemPin": typeof gameMaps_functions_updateItemPin;
  "gameMaps/functions/updateMap": typeof gameMaps_functions_updateMap;
  "gameMaps/functions/updatePinVisibility": typeof gameMaps_functions_updatePinVisibility;
  "gameMaps/mutations": typeof gameMaps_mutations;
  "gameMaps/queries": typeof gameMaps_queries;
  "gameMaps/triggers": typeof gameMaps_triggers;
  "gameMaps/types": typeof gameMaps_types;
  "gameMaps/validation": typeof gameMaps_validation;
  http: typeof http;
  "links/functions/getBacklinksForItem": typeof links_functions_getBacklinksForItem;
  "links/functions/getOutgoingLinksForNote": typeof links_functions_getOutgoingLinksForNote;
  "links/functions/syncNoteLinks": typeof links_functions_syncNoteLinks;
  "links/linkParsers": typeof links_linkParsers;
  "links/linkResolution": typeof links_linkResolution;
  "links/queries": typeof links_queries;
  "links/types": typeof links_types;
  "notes/blocknote": typeof notes_blocknote;
  "notes/editorSpecs": typeof notes_editorSpecs;
  "notes/functions/captureNoteSnapshot": typeof notes_functions_captureNoteSnapshot;
  "notes/functions/createNote": typeof notes_functions_createNote;
  "notes/functions/enhanceNote": typeof notes_functions_enhanceNote;
  "notes/functions/rollbackNote": typeof notes_functions_rollbackNote;
  "notes/functions/updateNote": typeof notes_functions_updateNote;
  "notes/mutations": typeof notes_mutations;
  "notes/queries": typeof notes_queries;
  "notes/triggers": typeof notes_triggers;
  "notes/types": typeof notes_types;
  "permissions/hasAtLeastPermissionLevel": typeof permissions_hasAtLeastPermissionLevel;
  "permissions/types": typeof permissions_types;
  "sessions/functions/endCurrentSession": typeof sessions_functions_endCurrentSession;
  "sessions/functions/getCurrentSession": typeof sessions_functions_getCurrentSession;
  "sessions/functions/getSession": typeof sessions_functions_getSession;
  "sessions/functions/getSessionsByCampaign": typeof sessions_functions_getSessionsByCampaign;
  "sessions/functions/setCurrentSession": typeof sessions_functions_setCurrentSession;
  "sessions/functions/startSession": typeof sessions_functions_startSession;
  "sessions/functions/updateSession": typeof sessions_functions_updateSession;
  "sessions/mutations": typeof sessions_mutations;
  "sessions/queries": typeof sessions_queries;
  "sessions/types": typeof sessions_types;
  "sidebarItems/functions/claimPreviewGeneration": typeof sidebarItems_functions_claimPreviewGeneration;
  "sidebarItems/functions/collectDescendants": typeof sidebarItems_functions_collectDescendants;
  "sidebarItems/functions/defaultItemName": typeof sidebarItems_functions_defaultItemName;
  "sidebarItems/functions/emptyTrashBin": typeof sidebarItems_functions_emptyTrashBin;
  "sidebarItems/functions/enhanceSidebarItem": typeof sidebarItems_functions_enhanceSidebarItem;
  "sidebarItems/functions/fetchCampaignSidebarItems": typeof sidebarItems_functions_fetchCampaignSidebarItems;
  "sidebarItems/functions/getSidebarItem": typeof sidebarItems_functions_getSidebarItem;
  "sidebarItems/functions/getSidebarItemBySlug": typeof sidebarItems_functions_getSidebarItemBySlug;
  "sidebarItems/functions/getSidebarItemWithContent": typeof sidebarItems_functions_getSidebarItemWithContent;
  "sidebarItems/functions/getSidebarItemsByParent": typeof sidebarItems_functions_getSidebarItemsByParent;
  "sidebarItems/functions/hardDeleteItem": typeof sidebarItems_functions_hardDeleteItem;
  "sidebarItems/functions/moveSidebarItem": typeof sidebarItems_functions_moveSidebarItem;
  "sidebarItems/functions/permanentlyDeleteSidebarItem": typeof sidebarItems_functions_permanentlyDeleteSidebarItem;
  "sidebarItems/functions/purgeExpiredTrash": typeof sidebarItems_functions_purgeExpiredTrash;
  "sidebarItems/functions/setPreviewImage": typeof sidebarItems_functions_setPreviewImage;
  "sidebarItems/functions/treeOperations": typeof sidebarItems_functions_treeOperations;
  "sidebarItems/internalMutations": typeof sidebarItems_internalMutations;
  "sidebarItems/mutations": typeof sidebarItems_mutations;
  "sidebarItems/queries": typeof sidebarItems_queries;
  "sidebarItems/schema/anySidebarItemValidator": typeof sidebarItems_schema_anySidebarItemValidator;
  "sidebarItems/schema/anySidebarItemWithContentValidator": typeof sidebarItems_schema_anySidebarItemWithContentValidator;
  "sidebarItems/schema/sidebarItemsTable": typeof sidebarItems_schema_sidebarItemsTable;
  "sidebarItems/schema/validators": typeof sidebarItems_schema_validators;
  "sidebarItems/sharedValidation": typeof sidebarItems_sharedValidation;
  "sidebarItems/triggerTypes": typeof sidebarItems_triggerTypes;
  "sidebarItems/triggers": typeof sidebarItems_triggers;
  "sidebarItems/types/baseTypes": typeof sidebarItems_types_baseTypes;
  "sidebarItems/types/types": typeof sidebarItems_types_types;
  "sidebarItems/validation": typeof sidebarItems_validation;
  "sidebarShares/functions/getSidebarItemShares": typeof sidebarShares_functions_getSidebarItemShares;
  "sidebarShares/functions/getSidebarItemSharesForItem": typeof sidebarShares_functions_getSidebarItemSharesForItem;
  "sidebarShares/functions/getSidebarItemWithShares": typeof sidebarShares_functions_getSidebarItemWithShares;
  "sidebarShares/functions/setAllPlayersPermission": typeof sidebarShares_functions_setAllPlayersPermission;
  "sidebarShares/functions/setFolderInheritShares": typeof sidebarShares_functions_setFolderInheritShares;
  "sidebarShares/functions/shareSidebarItem": typeof sidebarShares_functions_shareSidebarItem;
  "sidebarShares/functions/sidebarItemPermissions": typeof sidebarShares_functions_sidebarItemPermissions;
  "sidebarShares/functions/sidebarItemShareMutations": typeof sidebarShares_functions_sidebarItemShareMutations;
  "sidebarShares/functions/unshareSidebarItem": typeof sidebarShares_functions_unshareSidebarItem;
  "sidebarShares/mutations": typeof sidebarShares_mutations;
  "sidebarShares/queries": typeof sidebarShares_queries;
  "sidebarShares/types": typeof sidebarShares_types;
  "storage/functions/commitUpload": typeof storage_functions_commitUpload;
  "storage/functions/getDownloadUrl": typeof storage_functions_getDownloadUrl;
  "storage/functions/getStorageMetadata": typeof storage_functions_getStorageMetadata;
  "storage/functions/trackUpload": typeof storage_functions_trackUpload;
  "storage/mutations": typeof storage_mutations;
  "storage/queries": typeof storage_queries;
  "storage/types": typeof storage_types;
  "storage/validation": typeof storage_validation;
  triggers: typeof triggers;
  "userPreferences/mutations": typeof userPreferences_mutations;
  "userPreferences/queries": typeof userPreferences_queries;
  "userPreferences/types": typeof userPreferences_types;
  "users/constants": typeof users_constants;
  "users/functions/checkUsernameExists": typeof users_functions_checkUsernameExists;
  "users/functions/getUserProfile": typeof users_functions_getUserProfile;
  "users/mutations": typeof users_mutations;
  "users/queries": typeof users_queries;
  "users/types": typeof users_types;
  "users/validation": typeof users_validation;
  "yjsSync/constants": typeof yjsSync_constants;
  "yjsSync/functions/captureYjsState": typeof yjsSync_functions_captureYjsState;
  "yjsSync/functions/checkYjsAccess": typeof yjsSync_functions_checkYjsAccess;
  "yjsSync/functions/compactUpdates": typeof yjsSync_functions_compactUpdates;
  "yjsSync/functions/createYjsDocument": typeof yjsSync_functions_createYjsDocument;
  "yjsSync/functions/deleteYjsDocument": typeof yjsSync_functions_deleteYjsDocument;
  "yjsSync/functions/reconstructYDoc": typeof yjsSync_functions_reconstructYDoc;
  "yjsSync/functions/rollbackYjsDocument": typeof yjsSync_functions_rollbackYjsDocument;
  "yjsSync/functions/types": typeof yjsSync_functions_types;
  "yjsSync/functions/uint8ToArrayBuffer": typeof yjsSync_functions_uint8ToArrayBuffer;
  "yjsSync/internalMutations": typeof yjsSync_internalMutations;
  "yjsSync/mutations": typeof yjsSync_mutations;
  "yjsSync/queries": typeof yjsSync_queries;
}>;

/**
 * A utility for referencing Convex functions in your app's public API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;

/**
 * A utility for referencing Convex functions in your app's internal API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = internal.myModule.myFunction;
 * ```
 */
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;

export declare const components: {
  betterAuth: import("@convex-dev/better-auth/_generated/component.js").ComponentApi<"betterAuth">;
  resend: import("@convex-dev/resend/_generated/component.js").ComponentApi<"resend">;
};
