/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as auth__createAuth from "../auth/_createAuth.js";
import type * as auth_authBaseUrl from "../auth/authBaseUrl.js";
import type * as auth_component from "../auth/component.js";
import type * as auth_componentClient from "../auth/componentClient.js";
import type * as auth_functions_onCreateUser from "../auth/functions/onCreateUser.js";
import type * as auth_functions_onDeleteUser from "../auth/functions/onDeleteUser.js";
import type * as auth_functions_onUpdateUser from "../auth/functions/onUpdateUser.js";
import type * as auth_functions_purgeExpiredAuthData from "../auth/functions/purgeExpiredAuthData.js";
import type * as auth_httpActions from "../auth/httpActions.js";
import type * as auth_internalMutations from "../auth/internalMutations.js";
import type * as auth_routes from "../auth/routes.js";
import type * as blockShares_actions from "../blockShares/actions.js";
import type * as blockShares_functions_blockShareMutations from "../blockShares/functions/blockShareMutations.js";
import type * as blockShares_functions_getBlockPermissionLevel from "../blockShares/functions/getBlockPermissionLevel.js";
import type * as blockShares_functions_getBlockSharesForBlock from "../blockShares/functions/getBlockSharesForBlock.js";
import type * as blockShares_functions_setBlocksShareStatus from "../blockShares/functions/setBlocksShareStatus.js";
import type * as blockShares_functions_shareBlocks from "../blockShares/functions/shareBlocks.js";
import type * as blockShares_functions_unshareBlocks from "../blockShares/functions/unshareBlocks.js";
import type * as blockShares_internalMutations from "../blockShares/internalMutations.js";
import type * as blockShares_types from "../blockShares/types.js";
import type * as blocks_functions_extractPlainText from "../blocks/functions/extractPlainText.js";
import type * as blocks_functions_findBlockByBlockNoteId from "../blocks/functions/findBlockByBlockNoteId.js";
import type * as blocks_functions_flattenBlocks from "../blocks/functions/flattenBlocks.js";
import type * as blocks_functions_getAllBlocksByNote from "../blocks/functions/getAllBlocksByNote.js";
import type * as blocks_functions_getBlockWithShares from "../blocks/functions/getBlockWithShares.js";
import type * as blocks_functions_getBlocksWithShares from "../blocks/functions/getBlocksWithShares.js";
import type * as blocks_functions_getHeadingsByNote from "../blocks/functions/getHeadingsByNote.js";
import type * as blocks_functions_patchBlockMetadata from "../blocks/functions/patchBlockMetadata.js";
import type * as blocks_functions_reconstructBlockTree from "../blocks/functions/reconstructBlockTree.js";
import type * as blocks_functions_saveAllBlocksForNote from "../blocks/functions/saveAllBlocksForNote.js";
import type * as blocks_functions_searchBlocks from "../blocks/functions/searchBlocks.js";
import type * as blocks_parseEditorBlocks from "../blocks/parseEditorBlocks.js";
import type * as blocks_queries from "../blocks/queries.js";
import type * as blocks_types from "../blocks/types.js";
import type * as bookmarks_functions_getItemBookmark from "../bookmarks/functions/getItemBookmark.js";
import type * as bookmarks_functions_toggleItemBookmark from "../bookmarks/functions/toggleItemBookmark.js";
import type * as bookmarks_mutations from "../bookmarks/mutations.js";
import type * as bookmarks_types from "../bookmarks/types.js";
import type * as campaigns_constants from "../campaigns/constants.js";
import type * as campaigns_functions_createCampaign from "../campaigns/functions/createCampaign.js";
import type * as campaigns_functions_deleteCampaign from "../campaigns/functions/deleteCampaign.js";
import type * as campaigns_functions_getCampaign from "../campaigns/functions/getCampaign.js";
import type * as campaigns_functions_getCampaignMembers from "../campaigns/functions/getCampaignMembers.js";
import type * as campaigns_functions_getCampaignRequests from "../campaigns/functions/getCampaignRequests.js";
import type * as campaigns_functions_getUserCampaigns from "../campaigns/functions/getUserCampaigns.js";
import type * as campaigns_functions_joinCampaign from "../campaigns/functions/joinCampaign.js";
import type * as campaigns_functions_updateCampaign from "../campaigns/functions/updateCampaign.js";
import type * as campaigns_functions_updateCampaignMemberStatus from "../campaigns/functions/updateCampaignMemberStatus.js";
import type * as campaigns_mutations from "../campaigns/mutations.js";
import type * as campaigns_queries from "../campaigns/queries.js";
import type * as campaigns_types from "../campaigns/types.js";
import type * as campaigns_validation from "../campaigns/validation.js";
import type * as canvases_baseSchema from "../canvases/baseSchema.js";
import type * as canvases_functions_canvasCompanion from "../canvases/functions/canvasCompanion.js";
import type * as canvases_functions_enhanceCanvas from "../canvases/functions/enhanceCanvas.js";
import type * as canvases_functions_getCanvasForDownload from "../canvases/functions/getCanvasForDownload.js";
import type * as canvases_functions_rollbackCanvas from "../canvases/functions/rollbackCanvas.js";
import type * as canvases_triggers from "../canvases/triggers.js";
import type * as canvases_types from "../canvases/types.js";
import type * as common_async from "../common/async.js";
import type * as common_logger from "../common/logger.js";
import type * as common_slug from "../common/slug.js";
import type * as common_types from "../common/types.js";
import type * as crons from "../crons.js";
import type * as documentSnapshots_functions_createSnapshot from "../documentSnapshots/functions/createSnapshot.js";
import type * as documentSnapshots_functions_getSnapshot from "../documentSnapshots/functions/getSnapshot.js";
import type * as documentSnapshots_functions_rollbackToSnapshot from "../documentSnapshots/functions/rollbackToSnapshot.js";
import type * as documentSnapshots_mutations from "../documentSnapshots/mutations.js";
import type * as documentSnapshots_queries from "../documentSnapshots/queries.js";
import type * as documentSnapshots_types from "../documentSnapshots/types.js";
import type * as editHistory_log from "../editHistory/log.js";
import type * as editHistory_queries from "../editHistory/queries.js";
import type * as editHistory_types from "../editHistory/types.js";
import type * as editors_functions_getCurrentEditor from "../editors/functions/getCurrentEditor.js";
import type * as editors_functions_setCurrentEditor from "../editors/functions/setCurrentEditor.js";
import type * as editors_mutations from "../editors/mutations.js";
import type * as editors_queries from "../editors/queries.js";
import type * as editors_types from "../editors/types.js";
import type * as email from "../email.js";
import type * as emailHttpActions from "../emailHttpActions.js";
import type * as errors from "../errors.js";
import type * as files_functions_enhanceFile from "../files/functions/enhanceFile.js";
import type * as files_functions_fileCompanion from "../files/functions/fileCompanion.js";
import type * as files_functions_getFileForDownload from "../files/functions/getFileForDownload.js";
import type * as files_functions_updateFile from "../files/functions/updateFile.js";
import type * as files_mutations from "../files/mutations.js";
import type * as files_queries from "../files/queries.js";
import type * as files_triggers from "../files/triggers.js";
import type * as files_types from "../files/types.js";
import type * as folders_baseSchema from "../folders/baseSchema.js";
import type * as folders_functions_enhanceFolder from "../folders/functions/enhanceFolder.js";
import type * as folders_functions_folderCompanion from "../folders/functions/folderCompanion.js";
import type * as folders_functions_getItemsForDownload from "../folders/functions/getItemsForDownload.js";
import type * as folders_functions_getSidebarItemAncestors from "../folders/functions/getSidebarItemAncestors.js";
import type * as folders_queries from "../folders/queries.js";
import type * as folders_triggers from "../folders/triggers.js";
import type * as folders_types from "../folders/types.js";
import type * as functions from "../functions.js";
import type * as gameMaps_baseSchema from "../gameMaps/baseSchema.js";
import type * as gameMaps_functions_captureGameMapSnapshot from "../gameMaps/functions/captureGameMapSnapshot.js";
import type * as gameMaps_functions_createItemPins from "../gameMaps/functions/createItemPins.js";
import type * as gameMaps_functions_enhanceMap from "../gameMaps/functions/enhanceMap.js";
import type * as gameMaps_functions_getGameMapForDownload from "../gameMaps/functions/getGameMapForDownload.js";
import type * as gameMaps_functions_mapCompanion from "../gameMaps/functions/mapCompanion.js";
import type * as gameMaps_functions_removeItemPin from "../gameMaps/functions/removeItemPin.js";
import type * as gameMaps_functions_requirePinAccess from "../gameMaps/functions/requirePinAccess.js";
import type * as gameMaps_functions_rollbackGameMap from "../gameMaps/functions/rollbackGameMap.js";
import type * as gameMaps_functions_updateItemPin from "../gameMaps/functions/updateItemPin.js";
import type * as gameMaps_functions_updateMap from "../gameMaps/functions/updateMap.js";
import type * as gameMaps_functions_updatePinVisibility from "../gameMaps/functions/updatePinVisibility.js";
import type * as gameMaps_mutations from "../gameMaps/mutations.js";
import type * as gameMaps_queries from "../gameMaps/queries.js";
import type * as gameMaps_triggers from "../gameMaps/triggers.js";
import type * as gameMaps_types from "../gameMaps/types.js";
import type * as http from "../http.js";
import type * as httpBridge from "../httpBridge.js";
import type * as links_functions_getBacklinksForItem from "../links/functions/getBacklinksForItem.js";
import type * as links_functions_getOutgoingLinksForNote from "../links/functions/getOutgoingLinksForNote.js";
import type * as links_functions_resyncNoteLinksForNotes from "../links/functions/resyncNoteLinksForNotes.js";
import type * as links_functions_syncNoteLinks from "../links/functions/syncNoteLinks.js";
import type * as links_queries from "../links/queries.js";
import type * as links_types from "../links/types.js";
import type * as migrations from "../migrations.js";
import type * as noteValues_functions_noteValueRows from "../noteValues/functions/noteValueRows.js";
import type * as noteValues_functions_resolvePersistedNoteValueStates from "../noteValues/functions/resolvePersistedNoteValueStates.js";
import type * as noteValues_functions_saveAllNoteValuesForNote from "../noteValues/functions/saveAllNoteValuesForNote.js";
import type * as noteValues_queries from "../noteValues/queries.js";
import type * as notes_actions from "../notes/actions.js";
import type * as notes_blocknoteNode from "../notes/blocknoteNode.js";
import type * as notes_functions_enhanceNote from "../notes/functions/enhanceNote.js";
import type * as notes_functions_getNoteForDownload from "../notes/functions/getNoteForDownload.js";
import type * as notes_functions_noteCompanion from "../notes/functions/noteCompanion.js";
import type * as notes_functions_rollbackNote from "../notes/functions/rollbackNote.js";
import type * as notes_functions_syncNoteDerivedData from "../notes/functions/syncNoteDerivedData.js";
import type * as notes_internalActions from "../notes/internalActions.js";
import type * as notes_internalMutations from "../notes/internalMutations.js";
import type * as notes_internalQueries from "../notes/internalQueries.js";
import type * as notes_queries from "../notes/queries.js";
import type * as notes_triggers from "../notes/triggers.js";
import type * as notes_types from "../notes/types.js";
import type * as sessions_functions_endCurrentSession from "../sessions/functions/endCurrentSession.js";
import type * as sessions_functions_getCurrentSession from "../sessions/functions/getCurrentSession.js";
import type * as sessions_functions_getSession from "../sessions/functions/getSession.js";
import type * as sessions_functions_getSessionsByCampaign from "../sessions/functions/getSessionsByCampaign.js";
import type * as sessions_functions_setCurrentSession from "../sessions/functions/setCurrentSession.js";
import type * as sessions_functions_startSession from "../sessions/functions/startSession.js";
import type * as sessions_functions_updateSession from "../sessions/functions/updateSession.js";
import type * as sessions_mutations from "../sessions/mutations.js";
import type * as sessions_queries from "../sessions/queries.js";
import type * as sessions_types from "../sessions/types.js";
import type * as sidebarItems_filesystem___tests___testSidebarItem from "../sidebarItems/filesystem/__tests__/testSidebarItem.js";
import type * as sidebarItems_filesystem_access from "../sidebarItems/filesystem/access.js";
import type * as sidebarItems_filesystem_ancestors from "../sidebarItems/filesystem/ancestors.js";
import type * as sidebarItems_filesystem_capabilities from "../sidebarItems/filesystem/capabilities.js";
import type * as sidebarItems_filesystem_children from "../sidebarItems/filesystem/children.js";
import type * as sidebarItems_filesystem_commandModules_copy from "../sidebarItems/filesystem/commandModules/copy.js";
import type * as sidebarItems_filesystem_commandModules_create from "../sidebarItems/filesystem/commandModules/create.js";
import type * as sidebarItems_filesystem_commandModules_deleteForever from "../sidebarItems/filesystem/commandModules/deleteForever.js";
import type * as sidebarItems_filesystem_commandModules_emptyTrash from "../sidebarItems/filesystem/commandModules/emptyTrash.js";
import type * as sidebarItems_filesystem_commandModules_move from "../sidebarItems/filesystem/commandModules/move.js";
import type * as sidebarItems_filesystem_commandModules_rename from "../sidebarItems/filesystem/commandModules/rename.js";
import type * as sidebarItems_filesystem_companionInitialization from "../sidebarItems/filesystem/companionInitialization.js";
import type * as sidebarItems_filesystem_deltas from "../sidebarItems/filesystem/deltas.js";
import type * as sidebarItems_filesystem_mutations from "../sidebarItems/filesystem/mutations.js";
import type * as sidebarItems_filesystem_pathParentResolver from "../sidebarItems/filesystem/pathParentResolver.js";
import type * as sidebarItems_filesystem_siblings from "../sidebarItems/filesystem/siblings.js";
import type * as sidebarItems_filesystem_sidebarItemRows from "../sidebarItems/filesystem/sidebarItemRows.js";
import type * as sidebarItems_filesystem_sidebarItemWriter from "../sidebarItems/filesystem/sidebarItemWriter.js";
import type * as sidebarItems_filesystem_transactions from "../sidebarItems/filesystem/transactions.js";
import type * as sidebarItems_filesystem_treeWrites from "../sidebarItems/filesystem/treeWrites.js";
import type * as sidebarItems_filesystem_validators from "../sidebarItems/filesystem/validators.js";
import type * as sidebarItems_functions_applySidebarItemContentUpdate from "../sidebarItems/functions/applySidebarItemContentUpdate.js";
import type * as sidebarItems_functions_claimPreviewGeneration from "../sidebarItems/functions/claimPreviewGeneration.js";
import type * as sidebarItems_functions_collectDescendants from "../sidebarItems/functions/collectDescendants.js";
import type * as sidebarItems_functions_downloadTypes from "../sidebarItems/functions/downloadTypes.js";
import type * as sidebarItems_functions_enhanceBaseSidebarItem from "../sidebarItems/functions/enhanceBaseSidebarItem.js";
import type * as sidebarItems_functions_enhanceSidebarItem from "../sidebarItems/functions/enhanceSidebarItem.js";
import type * as sidebarItems_functions_fetchCampaignSidebarItems from "../sidebarItems/functions/fetchCampaignSidebarItems.js";
import type * as sidebarItems_functions_getSidebarItem from "../sidebarItems/functions/getSidebarItem.js";
import type * as sidebarItems_functions_getSidebarItemBySlug from "../sidebarItems/functions/getSidebarItemBySlug.js";
import type * as sidebarItems_functions_getSidebarItemWithContent from "../sidebarItems/functions/getSidebarItemWithContent.js";
import type * as sidebarItems_functions_getSidebarItemsByParent from "../sidebarItems/functions/getSidebarItemsByParent.js";
import type * as sidebarItems_functions_purgeExpiredTrash from "../sidebarItems/functions/purgeExpiredTrash.js";
import type * as sidebarItems_functions_setPreviewImage from "../sidebarItems/functions/setPreviewImage.js";
import type * as sidebarItems_internalMutations from "../sidebarItems/internalMutations.js";
import type * as sidebarItems_lifecycleMigration from "../sidebarItems/lifecycleMigration.js";
import type * as sidebarItems_mutations from "../sidebarItems/mutations.js";
import type * as sidebarItems_queries from "../sidebarItems/queries.js";
import type * as sidebarItems_schema_anySidebarItemValidator from "../sidebarItems/schema/anySidebarItemValidator.js";
import type * as sidebarItems_schema_anySidebarItemWithContentValidator from "../sidebarItems/schema/anySidebarItemWithContentValidator.js";
import type * as sidebarItems_schema_sidebarItemFields from "../sidebarItems/schema/sidebarItemFields.js";
import type * as sidebarItems_schema_sidebarItemsTable from "../sidebarItems/schema/sidebarItemsTable.js";
import type * as sidebarItems_schema_validators from "../sidebarItems/schema/validators.js";
import type * as sidebarItems_triggerTypes from "../sidebarItems/triggerTypes.js";
import type * as sidebarItems_triggers from "../sidebarItems/triggers.js";
import type * as sidebarItems_types_baseTypes from "../sidebarItems/types/baseTypes.js";
import type * as sidebarItems_types_status from "../sidebarItems/types/status.js";
import type * as sidebarItems_types_types from "../sidebarItems/types/types.js";
import type * as sidebarItems_validation_access from "../sidebarItems/validation/access.js";
import type * as sidebarItems_validation_name from "../sidebarItems/validation/name.js";
import type * as sidebarItems_validation_orchestration from "../sidebarItems/validation/orchestration.js";
import type * as sidebarItems_validation_parent from "../sidebarItems/validation/parent.js";
import type * as sidebarItems_validation_slug from "../sidebarItems/validation/slug.js";
import type * as sidebarShares_functions_getSidebarItemsWithShares from "../sidebarShares/functions/getSidebarItemsWithShares.js";
import type * as sidebarShares_functions_setAllPlayersPermissionForSidebarItems from "../sidebarShares/functions/setAllPlayersPermissionForSidebarItems.js";
import type * as sidebarShares_functions_setFolderInheritShares from "../sidebarShares/functions/setFolderInheritShares.js";
import type * as sidebarShares_functions_sidebarItemPermissions from "../sidebarShares/functions/sidebarItemPermissions.js";
import type * as sidebarShares_functions_sidebarItemShareMutations from "../sidebarShares/functions/sidebarItemShareMutations.js";
import type * as sidebarShares_mutations from "../sidebarShares/mutations.js";
import type * as sidebarShares_queries from "../sidebarShares/queries.js";
import type * as sidebarShares_types from "../sidebarShares/types.js";
import type * as storage_functions_commitUpload from "../storage/functions/commitUpload.js";
import type * as storage_functions_getDownloadUrl from "../storage/functions/getDownloadUrl.js";
import type * as storage_functions_getStorageMetadata from "../storage/functions/getStorageMetadata.js";
import type * as storage_functions_trackUpload from "../storage/functions/trackUpload.js";
import type * as storage_mutations from "../storage/mutations.js";
import type * as storage_queries from "../storage/queries.js";
import type * as storage_types from "../storage/types.js";
import type * as triggers from "../triggers.js";
import type * as userPreferences_mutations from "../userPreferences/mutations.js";
import type * as userPreferences_queries from "../userPreferences/queries.js";
import type * as userPreferences_types from "../userPreferences/types.js";
import type * as users_constants from "../users/constants.js";
import type * as users_functions_checkUsernameExists from "../users/functions/checkUsernameExists.js";
import type * as users_functions_getUserProfile from "../users/functions/getUserProfile.js";
import type * as users_mutations from "../users/mutations.js";
import type * as users_queries from "../users/queries.js";
import type * as users_types from "../users/types.js";
import type * as users_validation from "../users/validation.js";
import type * as yjsSync__yjsNode from "../yjsSync/_yjsNode.js";
import type * as yjsSync_constants from "../yjsSync/constants.js";
import type * as yjsSync_functions_checkYjsAccess from "../yjsSync/functions/checkYjsAccess.js";
import type * as yjsSync_functions_copyYjsUpdates from "../yjsSync/functions/copyYjsUpdates.js";
import type * as yjsSync_functions_createYjsDocument from "../yjsSync/functions/createYjsDocument.js";
import type * as yjsSync_functions_deleteYjsDocument from "../yjsSync/functions/deleteYjsDocument.js";
import type * as yjsSync_functions_rollbackYjsDocument from "../yjsSync/functions/rollbackYjsDocument.js";
import type * as yjsSync_functions_types from "../yjsSync/functions/types.js";
import type * as yjsSync_functions_uint8ToArrayBuffer from "../yjsSync/functions/uint8ToArrayBuffer.js";
import type * as yjsSync_internalActions from "../yjsSync/internalActions.js";
import type * as yjsSync_internalMutations from "../yjsSync/internalMutations.js";
import type * as yjsSync_internalQueries from "../yjsSync/internalQueries.js";
import type * as yjsSync_mutations from "../yjsSync/mutations.js";
import type * as yjsSync_queries from "../yjsSync/queries.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

declare const fullApi: ApiFromModules<{
  "auth/_createAuth": typeof auth__createAuth;
  "auth/authBaseUrl": typeof auth_authBaseUrl;
  "auth/component": typeof auth_component;
  "auth/componentClient": typeof auth_componentClient;
  "auth/functions/onCreateUser": typeof auth_functions_onCreateUser;
  "auth/functions/onDeleteUser": typeof auth_functions_onDeleteUser;
  "auth/functions/onUpdateUser": typeof auth_functions_onUpdateUser;
  "auth/functions/purgeExpiredAuthData": typeof auth_functions_purgeExpiredAuthData;
  "auth/httpActions": typeof auth_httpActions;
  "auth/internalMutations": typeof auth_internalMutations;
  "auth/routes": typeof auth_routes;
  "blockShares/actions": typeof blockShares_actions;
  "blockShares/functions/blockShareMutations": typeof blockShares_functions_blockShareMutations;
  "blockShares/functions/getBlockPermissionLevel": typeof blockShares_functions_getBlockPermissionLevel;
  "blockShares/functions/getBlockSharesForBlock": typeof blockShares_functions_getBlockSharesForBlock;
  "blockShares/functions/setBlocksShareStatus": typeof blockShares_functions_setBlocksShareStatus;
  "blockShares/functions/shareBlocks": typeof blockShares_functions_shareBlocks;
  "blockShares/functions/unshareBlocks": typeof blockShares_functions_unshareBlocks;
  "blockShares/internalMutations": typeof blockShares_internalMutations;
  "blockShares/types": typeof blockShares_types;
  "blocks/functions/extractPlainText": typeof blocks_functions_extractPlainText;
  "blocks/functions/findBlockByBlockNoteId": typeof blocks_functions_findBlockByBlockNoteId;
  "blocks/functions/flattenBlocks": typeof blocks_functions_flattenBlocks;
  "blocks/functions/getAllBlocksByNote": typeof blocks_functions_getAllBlocksByNote;
  "blocks/functions/getBlockWithShares": typeof blocks_functions_getBlockWithShares;
  "blocks/functions/getBlocksWithShares": typeof blocks_functions_getBlocksWithShares;
  "blocks/functions/getHeadingsByNote": typeof blocks_functions_getHeadingsByNote;
  "blocks/functions/patchBlockMetadata": typeof blocks_functions_patchBlockMetadata;
  "blocks/functions/reconstructBlockTree": typeof blocks_functions_reconstructBlockTree;
  "blocks/functions/saveAllBlocksForNote": typeof blocks_functions_saveAllBlocksForNote;
  "blocks/functions/searchBlocks": typeof blocks_functions_searchBlocks;
  "blocks/parseEditorBlocks": typeof blocks_parseEditorBlocks;
  "blocks/queries": typeof blocks_queries;
  "blocks/types": typeof blocks_types;
  "bookmarks/functions/getItemBookmark": typeof bookmarks_functions_getItemBookmark;
  "bookmarks/functions/toggleItemBookmark": typeof bookmarks_functions_toggleItemBookmark;
  "bookmarks/mutations": typeof bookmarks_mutations;
  "bookmarks/types": typeof bookmarks_types;
  "campaigns/constants": typeof campaigns_constants;
  "campaigns/functions/createCampaign": typeof campaigns_functions_createCampaign;
  "campaigns/functions/deleteCampaign": typeof campaigns_functions_deleteCampaign;
  "campaigns/functions/getCampaign": typeof campaigns_functions_getCampaign;
  "campaigns/functions/getCampaignMembers": typeof campaigns_functions_getCampaignMembers;
  "campaigns/functions/getCampaignRequests": typeof campaigns_functions_getCampaignRequests;
  "campaigns/functions/getUserCampaigns": typeof campaigns_functions_getUserCampaigns;
  "campaigns/functions/joinCampaign": typeof campaigns_functions_joinCampaign;
  "campaigns/functions/updateCampaign": typeof campaigns_functions_updateCampaign;
  "campaigns/functions/updateCampaignMemberStatus": typeof campaigns_functions_updateCampaignMemberStatus;
  "campaigns/mutations": typeof campaigns_mutations;
  "campaigns/queries": typeof campaigns_queries;
  "campaigns/types": typeof campaigns_types;
  "campaigns/validation": typeof campaigns_validation;
  "canvases/baseSchema": typeof canvases_baseSchema;
  "canvases/functions/canvasCompanion": typeof canvases_functions_canvasCompanion;
  "canvases/functions/enhanceCanvas": typeof canvases_functions_enhanceCanvas;
  "canvases/functions/getCanvasForDownload": typeof canvases_functions_getCanvasForDownload;
  "canvases/functions/rollbackCanvas": typeof canvases_functions_rollbackCanvas;
  "canvases/triggers": typeof canvases_triggers;
  "canvases/types": typeof canvases_types;
  "common/async": typeof common_async;
  "common/logger": typeof common_logger;
  "common/slug": typeof common_slug;
  "common/types": typeof common_types;
  crons: typeof crons;
  "documentSnapshots/functions/createSnapshot": typeof documentSnapshots_functions_createSnapshot;
  "documentSnapshots/functions/getSnapshot": typeof documentSnapshots_functions_getSnapshot;
  "documentSnapshots/functions/rollbackToSnapshot": typeof documentSnapshots_functions_rollbackToSnapshot;
  "documentSnapshots/mutations": typeof documentSnapshots_mutations;
  "documentSnapshots/queries": typeof documentSnapshots_queries;
  "documentSnapshots/types": typeof documentSnapshots_types;
  "editHistory/log": typeof editHistory_log;
  "editHistory/queries": typeof editHistory_queries;
  "editHistory/types": typeof editHistory_types;
  "editors/functions/getCurrentEditor": typeof editors_functions_getCurrentEditor;
  "editors/functions/setCurrentEditor": typeof editors_functions_setCurrentEditor;
  "editors/mutations": typeof editors_mutations;
  "editors/queries": typeof editors_queries;
  "editors/types": typeof editors_types;
  email: typeof email;
  emailHttpActions: typeof emailHttpActions;
  errors: typeof errors;
  "files/functions/enhanceFile": typeof files_functions_enhanceFile;
  "files/functions/fileCompanion": typeof files_functions_fileCompanion;
  "files/functions/getFileForDownload": typeof files_functions_getFileForDownload;
  "files/functions/updateFile": typeof files_functions_updateFile;
  "files/mutations": typeof files_mutations;
  "files/queries": typeof files_queries;
  "files/triggers": typeof files_triggers;
  "files/types": typeof files_types;
  "folders/baseSchema": typeof folders_baseSchema;
  "folders/functions/enhanceFolder": typeof folders_functions_enhanceFolder;
  "folders/functions/folderCompanion": typeof folders_functions_folderCompanion;
  "folders/functions/getItemsForDownload": typeof folders_functions_getItemsForDownload;
  "folders/functions/getSidebarItemAncestors": typeof folders_functions_getSidebarItemAncestors;
  "folders/queries": typeof folders_queries;
  "folders/triggers": typeof folders_triggers;
  "folders/types": typeof folders_types;
  functions: typeof functions;
  "gameMaps/baseSchema": typeof gameMaps_baseSchema;
  "gameMaps/functions/captureGameMapSnapshot": typeof gameMaps_functions_captureGameMapSnapshot;
  "gameMaps/functions/createItemPins": typeof gameMaps_functions_createItemPins;
  "gameMaps/functions/enhanceMap": typeof gameMaps_functions_enhanceMap;
  "gameMaps/functions/getGameMapForDownload": typeof gameMaps_functions_getGameMapForDownload;
  "gameMaps/functions/mapCompanion": typeof gameMaps_functions_mapCompanion;
  "gameMaps/functions/removeItemPin": typeof gameMaps_functions_removeItemPin;
  "gameMaps/functions/requirePinAccess": typeof gameMaps_functions_requirePinAccess;
  "gameMaps/functions/rollbackGameMap": typeof gameMaps_functions_rollbackGameMap;
  "gameMaps/functions/updateItemPin": typeof gameMaps_functions_updateItemPin;
  "gameMaps/functions/updateMap": typeof gameMaps_functions_updateMap;
  "gameMaps/functions/updatePinVisibility": typeof gameMaps_functions_updatePinVisibility;
  "gameMaps/mutations": typeof gameMaps_mutations;
  "gameMaps/queries": typeof gameMaps_queries;
  "gameMaps/triggers": typeof gameMaps_triggers;
  "gameMaps/types": typeof gameMaps_types;
  http: typeof http;
  httpBridge: typeof httpBridge;
  "links/functions/getBacklinksForItem": typeof links_functions_getBacklinksForItem;
  "links/functions/getOutgoingLinksForNote": typeof links_functions_getOutgoingLinksForNote;
  "links/functions/resyncNoteLinksForNotes": typeof links_functions_resyncNoteLinksForNotes;
  "links/functions/syncNoteLinks": typeof links_functions_syncNoteLinks;
  "links/queries": typeof links_queries;
  "links/types": typeof links_types;
  migrations: typeof migrations;
  "noteValues/functions/noteValueRows": typeof noteValues_functions_noteValueRows;
  "noteValues/functions/resolvePersistedNoteValueStates": typeof noteValues_functions_resolvePersistedNoteValueStates;
  "noteValues/functions/saveAllNoteValuesForNote": typeof noteValues_functions_saveAllNoteValuesForNote;
  "noteValues/queries": typeof noteValues_queries;
  "notes/actions": typeof notes_actions;
  "notes/blocknoteNode": typeof notes_blocknoteNode;
  "notes/functions/enhanceNote": typeof notes_functions_enhanceNote;
  "notes/functions/getNoteForDownload": typeof notes_functions_getNoteForDownload;
  "notes/functions/noteCompanion": typeof notes_functions_noteCompanion;
  "notes/functions/rollbackNote": typeof notes_functions_rollbackNote;
  "notes/functions/syncNoteDerivedData": typeof notes_functions_syncNoteDerivedData;
  "notes/internalActions": typeof notes_internalActions;
  "notes/internalMutations": typeof notes_internalMutations;
  "notes/internalQueries": typeof notes_internalQueries;
  "notes/queries": typeof notes_queries;
  "notes/triggers": typeof notes_triggers;
  "notes/types": typeof notes_types;
  "sessions/functions/endCurrentSession": typeof sessions_functions_endCurrentSession;
  "sessions/functions/getCurrentSession": typeof sessions_functions_getCurrentSession;
  "sessions/functions/getSession": typeof sessions_functions_getSession;
  "sessions/functions/getSessionsByCampaign": typeof sessions_functions_getSessionsByCampaign;
  "sessions/functions/setCurrentSession": typeof sessions_functions_setCurrentSession;
  "sessions/functions/startSession": typeof sessions_functions_startSession;
  "sessions/functions/updateSession": typeof sessions_functions_updateSession;
  "sessions/mutations": typeof sessions_mutations;
  "sessions/queries": typeof sessions_queries;
  "sessions/types": typeof sessions_types;
  "sidebarItems/filesystem/__tests__/testSidebarItem": typeof sidebarItems_filesystem___tests___testSidebarItem;
  "sidebarItems/filesystem/access": typeof sidebarItems_filesystem_access;
  "sidebarItems/filesystem/ancestors": typeof sidebarItems_filesystem_ancestors;
  "sidebarItems/filesystem/capabilities": typeof sidebarItems_filesystem_capabilities;
  "sidebarItems/filesystem/children": typeof sidebarItems_filesystem_children;
  "sidebarItems/filesystem/commandModules/copy": typeof sidebarItems_filesystem_commandModules_copy;
  "sidebarItems/filesystem/commandModules/create": typeof sidebarItems_filesystem_commandModules_create;
  "sidebarItems/filesystem/commandModules/deleteForever": typeof sidebarItems_filesystem_commandModules_deleteForever;
  "sidebarItems/filesystem/commandModules/emptyTrash": typeof sidebarItems_filesystem_commandModules_emptyTrash;
  "sidebarItems/filesystem/commandModules/move": typeof sidebarItems_filesystem_commandModules_move;
  "sidebarItems/filesystem/commandModules/rename": typeof sidebarItems_filesystem_commandModules_rename;
  "sidebarItems/filesystem/companionInitialization": typeof sidebarItems_filesystem_companionInitialization;
  "sidebarItems/filesystem/deltas": typeof sidebarItems_filesystem_deltas;
  "sidebarItems/filesystem/mutations": typeof sidebarItems_filesystem_mutations;
  "sidebarItems/filesystem/pathParentResolver": typeof sidebarItems_filesystem_pathParentResolver;
  "sidebarItems/filesystem/siblings": typeof sidebarItems_filesystem_siblings;
  "sidebarItems/filesystem/sidebarItemRows": typeof sidebarItems_filesystem_sidebarItemRows;
  "sidebarItems/filesystem/sidebarItemWriter": typeof sidebarItems_filesystem_sidebarItemWriter;
  "sidebarItems/filesystem/transactions": typeof sidebarItems_filesystem_transactions;
  "sidebarItems/filesystem/treeWrites": typeof sidebarItems_filesystem_treeWrites;
  "sidebarItems/filesystem/validators": typeof sidebarItems_filesystem_validators;
  "sidebarItems/functions/applySidebarItemContentUpdate": typeof sidebarItems_functions_applySidebarItemContentUpdate;
  "sidebarItems/functions/claimPreviewGeneration": typeof sidebarItems_functions_claimPreviewGeneration;
  "sidebarItems/functions/collectDescendants": typeof sidebarItems_functions_collectDescendants;
  "sidebarItems/functions/downloadTypes": typeof sidebarItems_functions_downloadTypes;
  "sidebarItems/functions/enhanceBaseSidebarItem": typeof sidebarItems_functions_enhanceBaseSidebarItem;
  "sidebarItems/functions/enhanceSidebarItem": typeof sidebarItems_functions_enhanceSidebarItem;
  "sidebarItems/functions/fetchCampaignSidebarItems": typeof sidebarItems_functions_fetchCampaignSidebarItems;
  "sidebarItems/functions/getSidebarItem": typeof sidebarItems_functions_getSidebarItem;
  "sidebarItems/functions/getSidebarItemBySlug": typeof sidebarItems_functions_getSidebarItemBySlug;
  "sidebarItems/functions/getSidebarItemWithContent": typeof sidebarItems_functions_getSidebarItemWithContent;
  "sidebarItems/functions/getSidebarItemsByParent": typeof sidebarItems_functions_getSidebarItemsByParent;
  "sidebarItems/functions/purgeExpiredTrash": typeof sidebarItems_functions_purgeExpiredTrash;
  "sidebarItems/functions/setPreviewImage": typeof sidebarItems_functions_setPreviewImage;
  "sidebarItems/internalMutations": typeof sidebarItems_internalMutations;
  "sidebarItems/lifecycleMigration": typeof sidebarItems_lifecycleMigration;
  "sidebarItems/mutations": typeof sidebarItems_mutations;
  "sidebarItems/queries": typeof sidebarItems_queries;
  "sidebarItems/schema/anySidebarItemValidator": typeof sidebarItems_schema_anySidebarItemValidator;
  "sidebarItems/schema/anySidebarItemWithContentValidator": typeof sidebarItems_schema_anySidebarItemWithContentValidator;
  "sidebarItems/schema/sidebarItemFields": typeof sidebarItems_schema_sidebarItemFields;
  "sidebarItems/schema/sidebarItemsTable": typeof sidebarItems_schema_sidebarItemsTable;
  "sidebarItems/schema/validators": typeof sidebarItems_schema_validators;
  "sidebarItems/triggerTypes": typeof sidebarItems_triggerTypes;
  "sidebarItems/triggers": typeof sidebarItems_triggers;
  "sidebarItems/types/baseTypes": typeof sidebarItems_types_baseTypes;
  "sidebarItems/types/status": typeof sidebarItems_types_status;
  "sidebarItems/types/types": typeof sidebarItems_types_types;
  "sidebarItems/validation/access": typeof sidebarItems_validation_access;
  "sidebarItems/validation/name": typeof sidebarItems_validation_name;
  "sidebarItems/validation/orchestration": typeof sidebarItems_validation_orchestration;
  "sidebarItems/validation/parent": typeof sidebarItems_validation_parent;
  "sidebarItems/validation/slug": typeof sidebarItems_validation_slug;
  "sidebarShares/functions/getSidebarItemsWithShares": typeof sidebarShares_functions_getSidebarItemsWithShares;
  "sidebarShares/functions/setAllPlayersPermissionForSidebarItems": typeof sidebarShares_functions_setAllPlayersPermissionForSidebarItems;
  "sidebarShares/functions/setFolderInheritShares": typeof sidebarShares_functions_setFolderInheritShares;
  "sidebarShares/functions/sidebarItemPermissions": typeof sidebarShares_functions_sidebarItemPermissions;
  "sidebarShares/functions/sidebarItemShareMutations": typeof sidebarShares_functions_sidebarItemShareMutations;
  "sidebarShares/mutations": typeof sidebarShares_mutations;
  "sidebarShares/queries": typeof sidebarShares_queries;
  "sidebarShares/types": typeof sidebarShares_types;
  "storage/functions/commitUpload": typeof storage_functions_commitUpload;
  "storage/functions/getDownloadUrl": typeof storage_functions_getDownloadUrl;
  "storage/functions/getStorageMetadata": typeof storage_functions_getStorageMetadata;
  "storage/functions/trackUpload": typeof storage_functions_trackUpload;
  "storage/mutations": typeof storage_mutations;
  "storage/queries": typeof storage_queries;
  "storage/types": typeof storage_types;
  triggers: typeof triggers;
  "userPreferences/mutations": typeof userPreferences_mutations;
  "userPreferences/queries": typeof userPreferences_queries;
  "userPreferences/types": typeof userPreferences_types;
  "users/constants": typeof users_constants;
  "users/functions/checkUsernameExists": typeof users_functions_checkUsernameExists;
  "users/functions/getUserProfile": typeof users_functions_getUserProfile;
  "users/mutations": typeof users_mutations;
  "users/queries": typeof users_queries;
  "users/types": typeof users_types;
  "users/validation": typeof users_validation;
  "yjsSync/_yjsNode": typeof yjsSync__yjsNode;
  "yjsSync/constants": typeof yjsSync_constants;
  "yjsSync/functions/checkYjsAccess": typeof yjsSync_functions_checkYjsAccess;
  "yjsSync/functions/copyYjsUpdates": typeof yjsSync_functions_copyYjsUpdates;
  "yjsSync/functions/createYjsDocument": typeof yjsSync_functions_createYjsDocument;
  "yjsSync/functions/deleteYjsDocument": typeof yjsSync_functions_deleteYjsDocument;
  "yjsSync/functions/rollbackYjsDocument": typeof yjsSync_functions_rollbackYjsDocument;
  "yjsSync/functions/types": typeof yjsSync_functions_types;
  "yjsSync/functions/uint8ToArrayBuffer": typeof yjsSync_functions_uint8ToArrayBuffer;
  "yjsSync/internalActions": typeof yjsSync_internalActions;
  "yjsSync/internalMutations": typeof yjsSync_internalMutations;
  "yjsSync/internalQueries": typeof yjsSync_internalQueries;
  "yjsSync/mutations": typeof yjsSync_mutations;
  "yjsSync/queries": typeof yjsSync_queries;
}>;

/**
 * A utility for referencing Convex functions in your app's public API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;

/**
 * A utility for referencing Convex functions in your app's internal API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = internal.myModule.myFunction;
 * ```
 */
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;

export declare const components: {
  betterAuth: import("@convex-dev/better-auth/_generated/component.js").ComponentApi<"betterAuth">;
  migrations: import("@convex-dev/migrations/_generated/component.js").ComponentApi<"migrations">;
  resend: import("@convex-dev/resend/_generated/component.js").ComponentApi<"resend">;
};
