/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSignUpRouteRouteImport } from './routes/_app/sign-up/route'
import { Route as AppSignInRouteRouteImport } from './routes/_app/sign-in/route'
import { Route as AppResetPasswordRouteRouteImport } from './routes/_app/reset-password/route'
import { Route as AppForgotPasswordRouteRouteImport } from './routes/_app/forgot-password/route'
import { Route as AppAuthRedirectRouteRouteImport } from './routes/_app/auth-redirect/route'
import { Route as AppAuthedRouteRouteImport } from './routes/_app/_authed/route'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppAuthedCampaignsRouteRouteImport } from './routes/_app/_authed/campaigns/route'
import { Route as AppAuthedCampaignsIndexRouteImport } from './routes/_app/_authed/campaigns/index'
import { Route as AppAuthedCampaignsCampaignIdRouteRouteImport } from './routes/_app/_authed/campaigns/$campaignId/route'
import { Route as AppJoinDmUsernameCampaignSlugIndexRouteImport } from './routes/_app/join.$dmUsername.$campaignSlug/index'
import { Route as AppAuthedCampaignsCampaignIdIndexRouteImport } from './routes/_app/_authed/campaigns/$campaignId/index'
import { Route as AppAuthedCampaignsCampaignIdEditorRouteRouteImport } from './routes/_app/_authed/campaigns/$campaignId/editor/route'
import { Route as AppAuthedCampaignsCampaignIdEditorIndexRouteImport } from './routes/_app/_authed/campaigns/$campaignId/editor/index'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSignUpRouteRoute = AppSignUpRouteRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AppRoute,
} as any)
const AppSignInRouteRoute = AppSignInRouteRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AppRoute,
} as any)
const AppResetPasswordRouteRoute = AppResetPasswordRouteRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AppRoute,
} as any)
const AppForgotPasswordRouteRoute = AppForgotPasswordRouteRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthRedirectRouteRoute = AppAuthRedirectRouteRouteImport.update({
  id: '/auth-redirect',
  path: '/auth-redirect',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthedRouteRoute = AppAuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAuthedCampaignsRouteRoute = AppAuthedCampaignsRouteRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AppAuthedRouteRoute,
} as any)
const AppAuthedCampaignsIndexRoute = AppAuthedCampaignsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAuthedCampaignsRouteRoute,
} as any)
const AppAuthedCampaignsCampaignIdRouteRoute =
  AppAuthedCampaignsCampaignIdRouteRouteImport.update({
    id: '/$campaignId',
    path: '/$campaignId',
    getParentRoute: () => AppAuthedCampaignsRouteRoute,
  } as any)
const AppJoinDmUsernameCampaignSlugIndexRoute =
  AppJoinDmUsernameCampaignSlugIndexRouteImport.update({
    id: '/join/$dmUsername/$campaignSlug/',
    path: '/join/$dmUsername/$campaignSlug/',
    getParentRoute: () => AppRoute,
  } as any)
const AppAuthedCampaignsCampaignIdIndexRoute =
  AppAuthedCampaignsCampaignIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppAuthedCampaignsCampaignIdRouteRoute,
  } as any)
const AppAuthedCampaignsCampaignIdEditorRouteRoute =
  AppAuthedCampaignsCampaignIdEditorRouteRouteImport.update({
    id: '/editor',
    path: '/editor',
    getParentRoute: () => AppAuthedCampaignsCampaignIdRouteRoute,
  } as any)
const AppAuthedCampaignsCampaignIdEditorIndexRoute =
  AppAuthedCampaignsCampaignIdEditorIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppAuthedCampaignsCampaignIdEditorRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/community': typeof CommunityRoute
  '/demo': typeof DemoRoute
  '/faq': typeof FaqRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/terms': typeof TermsRoute
  '/auth-redirect': typeof AppAuthRedirectRouteRoute
  '/forgot-password': typeof AppForgotPasswordRouteRoute
  '/reset-password': typeof AppResetPasswordRouteRoute
  '/sign-in': typeof AppSignInRouteRoute
  '/sign-up': typeof AppSignUpRouteRoute
  '/campaigns': typeof AppAuthedCampaignsRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/campaigns/$campaignId': typeof AppAuthedCampaignsCampaignIdRouteRouteWithChildren
  '/campaigns/': typeof AppAuthedCampaignsIndexRoute
  '/campaigns/$campaignId/editor': typeof AppAuthedCampaignsCampaignIdEditorRouteRouteWithChildren
  '/campaigns/$campaignId/': typeof AppAuthedCampaignsCampaignIdIndexRoute
  '/join/$dmUsername/$campaignSlug/': typeof AppJoinDmUsernameCampaignSlugIndexRoute
  '/campaigns/$campaignId/editor/': typeof AppAuthedCampaignsCampaignIdEditorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/community': typeof CommunityRoute
  '/demo': typeof DemoRoute
  '/faq': typeof FaqRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/terms': typeof TermsRoute
  '/auth-redirect': typeof AppAuthRedirectRouteRoute
  '/forgot-password': typeof AppForgotPasswordRouteRoute
  '/reset-password': typeof AppResetPasswordRouteRoute
  '/sign-in': typeof AppSignInRouteRoute
  '/sign-up': typeof AppSignUpRouteRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/campaigns': typeof AppAuthedCampaignsIndexRoute
  '/campaigns/$campaignId': typeof AppAuthedCampaignsCampaignIdIndexRoute
  '/join/$dmUsername/$campaignSlug': typeof AppJoinDmUsernameCampaignSlugIndexRoute
  '/campaigns/$campaignId/editor': typeof AppAuthedCampaignsCampaignIdEditorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/billing': typeof BillingRoute
  '/community': typeof CommunityRoute
  '/demo': typeof DemoRoute
  '/faq': typeof FaqRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/terms': typeof TermsRoute
  '/_app/_authed': typeof AppAuthedRouteRouteWithChildren
  '/_app/auth-redirect': typeof AppAuthRedirectRouteRoute
  '/_app/forgot-password': typeof AppForgotPasswordRouteRoute
  '/_app/reset-password': typeof AppResetPasswordRouteRoute
  '/_app/sign-in': typeof AppSignInRouteRoute
  '/_app/sign-up': typeof AppSignUpRouteRoute
  '/_app/_authed/campaigns': typeof AppAuthedCampaignsRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/_authed/campaigns/$campaignId': typeof AppAuthedCampaignsCampaignIdRouteRouteWithChildren
  '/_app/_authed/campaigns/': typeof AppAuthedCampaignsIndexRoute
  '/_app/_authed/campaigns/$campaignId/editor': typeof AppAuthedCampaignsCampaignIdEditorRouteRouteWithChildren
  '/_app/_authed/campaigns/$campaignId/': typeof AppAuthedCampaignsCampaignIdIndexRoute
  '/_app/join/$dmUsername/$campaignSlug/': typeof AppJoinDmUsernameCampaignSlugIndexRoute
  '/_app/_authed/campaigns/$campaignId/editor/': typeof AppAuthedCampaignsCampaignIdEditorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/billing'
    | '/community'
    | '/demo'
    | '/faq'
    | '/pricing'
    | '/privacy'
    | '/security'
    | '/terms'
    | '/auth-redirect'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/campaigns'
    | '/api/auth/$'
    | '/campaigns/$campaignId'
    | '/campaigns/'
    | '/campaigns/$campaignId/editor'
    | '/campaigns/$campaignId/'
    | '/join/$dmUsername/$campaignSlug/'
    | '/campaigns/$campaignId/editor/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/billing'
    | '/community'
    | '/demo'
    | '/faq'
    | '/pricing'
    | '/privacy'
    | '/security'
    | '/terms'
    | '/auth-redirect'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/api/auth/$'
    | '/campaigns'
    | '/campaigns/$campaignId'
    | '/join/$dmUsername/$campaignSlug'
    | '/campaigns/$campaignId/editor'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/billing'
    | '/community'
    | '/demo'
    | '/faq'
    | '/pricing'
    | '/privacy'
    | '/security'
    | '/terms'
    | '/_app/_authed'
    | '/_app/auth-redirect'
    | '/_app/forgot-password'
    | '/_app/reset-password'
    | '/_app/sign-in'
    | '/_app/sign-up'
    | '/_app/_authed/campaigns'
    | '/api/auth/$'
    | '/_app/_authed/campaigns/$campaignId'
    | '/_app/_authed/campaigns/'
    | '/_app/_authed/campaigns/$campaignId/editor'
    | '/_app/_authed/campaigns/$campaignId/'
    | '/_app/join/$dmUsername/$campaignSlug/'
    | '/_app/_authed/campaigns/$campaignId/editor/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  BillingRoute: typeof BillingRoute
  CommunityRoute: typeof CommunityRoute
  DemoRoute: typeof DemoRoute
  FaqRoute: typeof FaqRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  SecurityRoute: typeof SecurityRoute
  TermsRoute: typeof TermsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/sign-up': {
      id: '/_app/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AppSignUpRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sign-in': {
      id: '/_app/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AppSignInRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reset-password': {
      id: '/_app/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AppResetPasswordRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/forgot-password': {
      id: '/_app/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AppForgotPasswordRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/auth-redirect': {
      id: '/_app/auth-redirect'
      path: '/auth-redirect'
      fullPath: '/auth-redirect'
      preLoaderRoute: typeof AppAuthRedirectRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_authed': {
      id: '/_app/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppAuthedRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/_authed/campaigns': {
      id: '/_app/_authed/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof AppAuthedCampaignsRouteRouteImport
      parentRoute: typeof AppAuthedRouteRoute
    }
    '/_app/_authed/campaigns/': {
      id: '/_app/_authed/campaigns/'
      path: '/'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof AppAuthedCampaignsIndexRouteImport
      parentRoute: typeof AppAuthedCampaignsRouteRoute
    }
    '/_app/_authed/campaigns/$campaignId': {
      id: '/_app/_authed/campaigns/$campaignId'
      path: '/$campaignId'
      fullPath: '/campaigns/$campaignId'
      preLoaderRoute: typeof AppAuthedCampaignsCampaignIdRouteRouteImport
      parentRoute: typeof AppAuthedCampaignsRouteRoute
    }
    '/_app/join/$dmUsername/$campaignSlug/': {
      id: '/_app/join/$dmUsername/$campaignSlug/'
      path: '/join/$dmUsername/$campaignSlug'
      fullPath: '/join/$dmUsername/$campaignSlug/'
      preLoaderRoute: typeof AppJoinDmUsernameCampaignSlugIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_authed/campaigns/$campaignId/': {
      id: '/_app/_authed/campaigns/$campaignId/'
      path: '/'
      fullPath: '/campaigns/$campaignId/'
      preLoaderRoute: typeof AppAuthedCampaignsCampaignIdIndexRouteImport
      parentRoute: typeof AppAuthedCampaignsCampaignIdRouteRoute
    }
    '/_app/_authed/campaigns/$campaignId/editor': {
      id: '/_app/_authed/campaigns/$campaignId/editor'
      path: '/editor'
      fullPath: '/campaigns/$campaignId/editor'
      preLoaderRoute: typeof AppAuthedCampaignsCampaignIdEditorRouteRouteImport
      parentRoute: typeof AppAuthedCampaignsCampaignIdRouteRoute
    }
    '/_app/_authed/campaigns/$campaignId/editor/': {
      id: '/_app/_authed/campaigns/$campaignId/editor/'
      path: '/'
      fullPath: '/campaigns/$campaignId/editor/'
      preLoaderRoute: typeof AppAuthedCampaignsCampaignIdEditorIndexRouteImport
      parentRoute: typeof AppAuthedCampaignsCampaignIdEditorRouteRoute
    }
  }
}

interface AppAuthedCampaignsCampaignIdEditorRouteRouteChildren {
  AppAuthedCampaignsCampaignIdEditorIndexRoute: typeof AppAuthedCampaignsCampaignIdEditorIndexRoute
}

const AppAuthedCampaignsCampaignIdEditorRouteRouteChildren: AppAuthedCampaignsCampaignIdEditorRouteRouteChildren =
  {
    AppAuthedCampaignsCampaignIdEditorIndexRoute:
      AppAuthedCampaignsCampaignIdEditorIndexRoute,
  }

const AppAuthedCampaignsCampaignIdEditorRouteRouteWithChildren =
  AppAuthedCampaignsCampaignIdEditorRouteRoute._addFileChildren(
    AppAuthedCampaignsCampaignIdEditorRouteRouteChildren,
  )

interface AppAuthedCampaignsCampaignIdRouteRouteChildren {
  AppAuthedCampaignsCampaignIdEditorRouteRoute: typeof AppAuthedCampaignsCampaignIdEditorRouteRouteWithChildren
  AppAuthedCampaignsCampaignIdIndexRoute: typeof AppAuthedCampaignsCampaignIdIndexRoute
}

const AppAuthedCampaignsCampaignIdRouteRouteChildren: AppAuthedCampaignsCampaignIdRouteRouteChildren =
  {
    AppAuthedCampaignsCampaignIdEditorRouteRoute:
      AppAuthedCampaignsCampaignIdEditorRouteRouteWithChildren,
    AppAuthedCampaignsCampaignIdIndexRoute:
      AppAuthedCampaignsCampaignIdIndexRoute,
  }

const AppAuthedCampaignsCampaignIdRouteRouteWithChildren =
  AppAuthedCampaignsCampaignIdRouteRoute._addFileChildren(
    AppAuthedCampaignsCampaignIdRouteRouteChildren,
  )

interface AppAuthedCampaignsRouteRouteChildren {
  AppAuthedCampaignsCampaignIdRouteRoute: typeof AppAuthedCampaignsCampaignIdRouteRouteWithChildren
  AppAuthedCampaignsIndexRoute: typeof AppAuthedCampaignsIndexRoute
}

const AppAuthedCampaignsRouteRouteChildren: AppAuthedCampaignsRouteRouteChildren =
  {
    AppAuthedCampaignsCampaignIdRouteRoute:
      AppAuthedCampaignsCampaignIdRouteRouteWithChildren,
    AppAuthedCampaignsIndexRoute: AppAuthedCampaignsIndexRoute,
  }

const AppAuthedCampaignsRouteRouteWithChildren =
  AppAuthedCampaignsRouteRoute._addFileChildren(
    AppAuthedCampaignsRouteRouteChildren,
  )

interface AppAuthedRouteRouteChildren {
  AppAuthedCampaignsRouteRoute: typeof AppAuthedCampaignsRouteRouteWithChildren
}

const AppAuthedRouteRouteChildren: AppAuthedRouteRouteChildren = {
  AppAuthedCampaignsRouteRoute: AppAuthedCampaignsRouteRouteWithChildren,
}

const AppAuthedRouteRouteWithChildren = AppAuthedRouteRoute._addFileChildren(
  AppAuthedRouteRouteChildren,
)

interface AppRouteChildren {
  AppAuthedRouteRoute: typeof AppAuthedRouteRouteWithChildren
  AppAuthRedirectRouteRoute: typeof AppAuthRedirectRouteRoute
  AppForgotPasswordRouteRoute: typeof AppForgotPasswordRouteRoute
  AppResetPasswordRouteRoute: typeof AppResetPasswordRouteRoute
  AppSignInRouteRoute: typeof AppSignInRouteRoute
  AppSignUpRouteRoute: typeof AppSignUpRouteRoute
  AppJoinDmUsernameCampaignSlugIndexRoute: typeof AppJoinDmUsernameCampaignSlugIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAuthedRouteRoute: AppAuthedRouteRouteWithChildren,
  AppAuthRedirectRouteRoute: AppAuthRedirectRouteRoute,
  AppForgotPasswordRouteRoute: AppForgotPasswordRouteRoute,
  AppResetPasswordRouteRoute: AppResetPasswordRouteRoute,
  AppSignInRouteRoute: AppSignInRouteRoute,
  AppSignUpRouteRoute: AppSignUpRouteRoute,
  AppJoinDmUsernameCampaignSlugIndexRoute:
    AppJoinDmUsernameCampaignSlugIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  BillingRoute: BillingRoute,
  CommunityRoute: CommunityRoute,
  DemoRoute: DemoRoute,
  FaqRoute: FaqRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  SecurityRoute: SecurityRoute,
  TermsRoute: TermsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
