/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteRouteImport } from './routes/sign-up/route'
import { Route as SignInRouteRouteImport } from './routes/sign-in/route'
import { Route as AuthRedirectRouteRouteImport } from './routes/auth-redirect/route'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedCampaignsRouteRouteImport } from './routes/_authed/campaigns/route'
import { Route as AuthedCampaignsIndexRouteImport } from './routes/_authed/campaigns/index'
import { Route as JoinDmUsernameCampaignSlugIndexRouteImport } from './routes/join.$dmUsername.$campaignSlug/index'
import { Route as AuthedCampaignsDmUsernameCampaignSlugRouteRouteImport } from './routes/_authed/campaigns/$dmUsername.$campaignSlug/route'
import { Route as AuthedCampaignsDmUsernameCampaignSlugIndexRouteImport } from './routes/_authed/campaigns/$dmUsername.$campaignSlug/index'
import { Route as AuthedCampaignsDmUsernameCampaignSlugPlayersRouteRouteImport } from './routes/_authed/campaigns/$dmUsername.$campaignSlug/players/route'
import { Route as AuthedCampaignsDmUsernameCampaignSlugEditorRouteRouteImport } from './routes/_authed/campaigns/$dmUsername.$campaignSlug/editor/route'
import { Route as AuthedCampaignsDmUsernameCampaignSlugSettingsIndexRouteImport } from './routes/_authed/campaigns/$dmUsername.$campaignSlug/settings/index'
import { Route as AuthedCampaignsDmUsernameCampaignSlugPlayersIndexRouteImport } from './routes/_authed/campaigns/$dmUsername.$campaignSlug/players/index'
import { Route as AuthedCampaignsDmUsernameCampaignSlugEditorIndexRouteImport } from './routes/_authed/campaigns/$dmUsername.$campaignSlug/editor/index'
import { Route as AuthedCampaignsDmUsernameCampaignSlugPlayersPlayerIdRouteImport } from './routes/_authed/campaigns/$dmUsername.$campaignSlug/players/$playerId'

const SignUpRouteRoute = SignUpRouteRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRouteRoute = SignInRouteRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRedirectRouteRoute = AuthRedirectRouteRouteImport.update({
  id: '/auth-redirect',
  path: '/auth-redirect',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedCampaignsRouteRoute = AuthedCampaignsRouteRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedCampaignsIndexRoute = AuthedCampaignsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedCampaignsRouteRoute,
} as any)
const JoinDmUsernameCampaignSlugIndexRoute =
  JoinDmUsernameCampaignSlugIndexRouteImport.update({
    id: '/join/$dmUsername/$campaignSlug/',
    path: '/join/$dmUsername/$campaignSlug/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthedCampaignsDmUsernameCampaignSlugRouteRoute =
  AuthedCampaignsDmUsernameCampaignSlugRouteRouteImport.update({
    id: '/$dmUsername/$campaignSlug',
    path: '/$dmUsername/$campaignSlug',
    getParentRoute: () => AuthedCampaignsRouteRoute,
  } as any)
const AuthedCampaignsDmUsernameCampaignSlugIndexRoute =
  AuthedCampaignsDmUsernameCampaignSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedCampaignsDmUsernameCampaignSlugRouteRoute,
  } as any)
const AuthedCampaignsDmUsernameCampaignSlugPlayersRouteRoute =
  AuthedCampaignsDmUsernameCampaignSlugPlayersRouteRouteImport.update({
    id: '/players',
    path: '/players',
    getParentRoute: () => AuthedCampaignsDmUsernameCampaignSlugRouteRoute,
  } as any)
const AuthedCampaignsDmUsernameCampaignSlugEditorRouteRoute =
  AuthedCampaignsDmUsernameCampaignSlugEditorRouteRouteImport.update({
    id: '/editor',
    path: '/editor',
    getParentRoute: () => AuthedCampaignsDmUsernameCampaignSlugRouteRoute,
  } as any)
const AuthedCampaignsDmUsernameCampaignSlugSettingsIndexRoute =
  AuthedCampaignsDmUsernameCampaignSlugSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthedCampaignsDmUsernameCampaignSlugRouteRoute,
  } as any)
const AuthedCampaignsDmUsernameCampaignSlugPlayersIndexRoute =
  AuthedCampaignsDmUsernameCampaignSlugPlayersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () =>
      AuthedCampaignsDmUsernameCampaignSlugPlayersRouteRoute,
  } as any)
const AuthedCampaignsDmUsernameCampaignSlugEditorIndexRoute =
  AuthedCampaignsDmUsernameCampaignSlugEditorIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedCampaignsDmUsernameCampaignSlugEditorRouteRoute,
  } as any)
const AuthedCampaignsDmUsernameCampaignSlugPlayersPlayerIdRoute =
  AuthedCampaignsDmUsernameCampaignSlugPlayersPlayerIdRouteImport.update({
    id: '/$playerId',
    path: '/$playerId',
    getParentRoute: () =>
      AuthedCampaignsDmUsernameCampaignSlugPlayersRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth-redirect': typeof AuthRedirectRouteRoute
  '/sign-in': typeof SignInRouteRoute
  '/sign-up': typeof SignUpRouteRoute
  '/campaigns': typeof AuthedCampaignsRouteRouteWithChildren
  '/campaigns/': typeof AuthedCampaignsIndexRoute
  '/campaigns/$dmUsername/$campaignSlug': typeof AuthedCampaignsDmUsernameCampaignSlugRouteRouteWithChildren
  '/join/$dmUsername/$campaignSlug': typeof JoinDmUsernameCampaignSlugIndexRoute
  '/campaigns/$dmUsername/$campaignSlug/editor': typeof AuthedCampaignsDmUsernameCampaignSlugEditorRouteRouteWithChildren
  '/campaigns/$dmUsername/$campaignSlug/players': typeof AuthedCampaignsDmUsernameCampaignSlugPlayersRouteRouteWithChildren
  '/campaigns/$dmUsername/$campaignSlug/': typeof AuthedCampaignsDmUsernameCampaignSlugIndexRoute
  '/campaigns/$dmUsername/$campaignSlug/players/$playerId': typeof AuthedCampaignsDmUsernameCampaignSlugPlayersPlayerIdRoute
  '/campaigns/$dmUsername/$campaignSlug/editor/': typeof AuthedCampaignsDmUsernameCampaignSlugEditorIndexRoute
  '/campaigns/$dmUsername/$campaignSlug/players/': typeof AuthedCampaignsDmUsernameCampaignSlugPlayersIndexRoute
  '/campaigns/$dmUsername/$campaignSlug/settings': typeof AuthedCampaignsDmUsernameCampaignSlugSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth-redirect': typeof AuthRedirectRouteRoute
  '/sign-in': typeof SignInRouteRoute
  '/sign-up': typeof SignUpRouteRoute
  '/campaigns': typeof AuthedCampaignsIndexRoute
  '/join/$dmUsername/$campaignSlug': typeof JoinDmUsernameCampaignSlugIndexRoute
  '/campaigns/$dmUsername/$campaignSlug': typeof AuthedCampaignsDmUsernameCampaignSlugIndexRoute
  '/campaigns/$dmUsername/$campaignSlug/players/$playerId': typeof AuthedCampaignsDmUsernameCampaignSlugPlayersPlayerIdRoute
  '/campaigns/$dmUsername/$campaignSlug/editor': typeof AuthedCampaignsDmUsernameCampaignSlugEditorIndexRoute
  '/campaigns/$dmUsername/$campaignSlug/players': typeof AuthedCampaignsDmUsernameCampaignSlugPlayersIndexRoute
  '/campaigns/$dmUsername/$campaignSlug/settings': typeof AuthedCampaignsDmUsernameCampaignSlugSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/auth-redirect': typeof AuthRedirectRouteRoute
  '/sign-in': typeof SignInRouteRoute
  '/sign-up': typeof SignUpRouteRoute
  '/_authed/campaigns': typeof AuthedCampaignsRouteRouteWithChildren
  '/_authed/campaigns/': typeof AuthedCampaignsIndexRoute
  '/_authed/campaigns/$dmUsername/$campaignSlug': typeof AuthedCampaignsDmUsernameCampaignSlugRouteRouteWithChildren
  '/join/$dmUsername/$campaignSlug/': typeof JoinDmUsernameCampaignSlugIndexRoute
  '/_authed/campaigns/$dmUsername/$campaignSlug/editor': typeof AuthedCampaignsDmUsernameCampaignSlugEditorRouteRouteWithChildren
  '/_authed/campaigns/$dmUsername/$campaignSlug/players': typeof AuthedCampaignsDmUsernameCampaignSlugPlayersRouteRouteWithChildren
  '/_authed/campaigns/$dmUsername/$campaignSlug/': typeof AuthedCampaignsDmUsernameCampaignSlugIndexRoute
  '/_authed/campaigns/$dmUsername/$campaignSlug/players/$playerId': typeof AuthedCampaignsDmUsernameCampaignSlugPlayersPlayerIdRoute
  '/_authed/campaigns/$dmUsername/$campaignSlug/editor/': typeof AuthedCampaignsDmUsernameCampaignSlugEditorIndexRoute
  '/_authed/campaigns/$dmUsername/$campaignSlug/players/': typeof AuthedCampaignsDmUsernameCampaignSlugPlayersIndexRoute
  '/_authed/campaigns/$dmUsername/$campaignSlug/settings/': typeof AuthedCampaignsDmUsernameCampaignSlugSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth-redirect'
    | '/sign-in'
    | '/sign-up'
    | '/campaigns'
    | '/campaigns/'
    | '/campaigns/$dmUsername/$campaignSlug'
    | '/join/$dmUsername/$campaignSlug'
    | '/campaigns/$dmUsername/$campaignSlug/editor'
    | '/campaigns/$dmUsername/$campaignSlug/players'
    | '/campaigns/$dmUsername/$campaignSlug/'
    | '/campaigns/$dmUsername/$campaignSlug/players/$playerId'
    | '/campaigns/$dmUsername/$campaignSlug/editor/'
    | '/campaigns/$dmUsername/$campaignSlug/players/'
    | '/campaigns/$dmUsername/$campaignSlug/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth-redirect'
    | '/sign-in'
    | '/sign-up'
    | '/campaigns'
    | '/join/$dmUsername/$campaignSlug'
    | '/campaigns/$dmUsername/$campaignSlug'
    | '/campaigns/$dmUsername/$campaignSlug/players/$playerId'
    | '/campaigns/$dmUsername/$campaignSlug/editor'
    | '/campaigns/$dmUsername/$campaignSlug/players'
    | '/campaigns/$dmUsername/$campaignSlug/settings'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/auth-redirect'
    | '/sign-in'
    | '/sign-up'
    | '/_authed/campaigns'
    | '/_authed/campaigns/'
    | '/_authed/campaigns/$dmUsername/$campaignSlug'
    | '/join/$dmUsername/$campaignSlug/'
    | '/_authed/campaigns/$dmUsername/$campaignSlug/editor'
    | '/_authed/campaigns/$dmUsername/$campaignSlug/players'
    | '/_authed/campaigns/$dmUsername/$campaignSlug/'
    | '/_authed/campaigns/$dmUsername/$campaignSlug/players/$playerId'
    | '/_authed/campaigns/$dmUsername/$campaignSlug/editor/'
    | '/_authed/campaigns/$dmUsername/$campaignSlug/players/'
    | '/_authed/campaigns/$dmUsername/$campaignSlug/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  AuthRedirectRouteRoute: typeof AuthRedirectRouteRoute
  SignInRouteRoute: typeof SignInRouteRoute
  SignUpRouteRoute: typeof SignUpRouteRoute
  JoinDmUsernameCampaignSlugIndexRoute: typeof JoinDmUsernameCampaignSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-redirect': {
      id: '/auth-redirect'
      path: '/auth-redirect'
      fullPath: '/auth-redirect'
      preLoaderRoute: typeof AuthRedirectRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/campaigns': {
      id: '/_authed/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof AuthedCampaignsRouteRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/campaigns/': {
      id: '/_authed/campaigns/'
      path: '/'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof AuthedCampaignsIndexRouteImport
      parentRoute: typeof AuthedCampaignsRouteRoute
    }
    '/join/$dmUsername/$campaignSlug/': {
      id: '/join/$dmUsername/$campaignSlug/'
      path: '/join/$dmUsername/$campaignSlug'
      fullPath: '/join/$dmUsername/$campaignSlug'
      preLoaderRoute: typeof JoinDmUsernameCampaignSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/campaigns/$dmUsername/$campaignSlug': {
      id: '/_authed/campaigns/$dmUsername/$campaignSlug'
      path: '/$dmUsername/$campaignSlug'
      fullPath: '/campaigns/$dmUsername/$campaignSlug'
      preLoaderRoute: typeof AuthedCampaignsDmUsernameCampaignSlugRouteRouteImport
      parentRoute: typeof AuthedCampaignsRouteRoute
    }
    '/_authed/campaigns/$dmUsername/$campaignSlug/': {
      id: '/_authed/campaigns/$dmUsername/$campaignSlug/'
      path: '/'
      fullPath: '/campaigns/$dmUsername/$campaignSlug/'
      preLoaderRoute: typeof AuthedCampaignsDmUsernameCampaignSlugIndexRouteImport
      parentRoute: typeof AuthedCampaignsDmUsernameCampaignSlugRouteRoute
    }
    '/_authed/campaigns/$dmUsername/$campaignSlug/players': {
      id: '/_authed/campaigns/$dmUsername/$campaignSlug/players'
      path: '/players'
      fullPath: '/campaigns/$dmUsername/$campaignSlug/players'
      preLoaderRoute: typeof AuthedCampaignsDmUsernameCampaignSlugPlayersRouteRouteImport
      parentRoute: typeof AuthedCampaignsDmUsernameCampaignSlugRouteRoute
    }
    '/_authed/campaigns/$dmUsername/$campaignSlug/editor': {
      id: '/_authed/campaigns/$dmUsername/$campaignSlug/editor'
      path: '/editor'
      fullPath: '/campaigns/$dmUsername/$campaignSlug/editor'
      preLoaderRoute: typeof AuthedCampaignsDmUsernameCampaignSlugEditorRouteRouteImport
      parentRoute: typeof AuthedCampaignsDmUsernameCampaignSlugRouteRoute
    }
    '/_authed/campaigns/$dmUsername/$campaignSlug/settings/': {
      id: '/_authed/campaigns/$dmUsername/$campaignSlug/settings/'
      path: '/settings'
      fullPath: '/campaigns/$dmUsername/$campaignSlug/settings'
      preLoaderRoute: typeof AuthedCampaignsDmUsernameCampaignSlugSettingsIndexRouteImport
      parentRoute: typeof AuthedCampaignsDmUsernameCampaignSlugRouteRoute
    }
    '/_authed/campaigns/$dmUsername/$campaignSlug/players/': {
      id: '/_authed/campaigns/$dmUsername/$campaignSlug/players/'
      path: '/'
      fullPath: '/campaigns/$dmUsername/$campaignSlug/players/'
      preLoaderRoute: typeof AuthedCampaignsDmUsernameCampaignSlugPlayersIndexRouteImport
      parentRoute: typeof AuthedCampaignsDmUsernameCampaignSlugPlayersRouteRoute
    }
    '/_authed/campaigns/$dmUsername/$campaignSlug/editor/': {
      id: '/_authed/campaigns/$dmUsername/$campaignSlug/editor/'
      path: '/'
      fullPath: '/campaigns/$dmUsername/$campaignSlug/editor/'
      preLoaderRoute: typeof AuthedCampaignsDmUsernameCampaignSlugEditorIndexRouteImport
      parentRoute: typeof AuthedCampaignsDmUsernameCampaignSlugEditorRouteRoute
    }
    '/_authed/campaigns/$dmUsername/$campaignSlug/players/$playerId': {
      id: '/_authed/campaigns/$dmUsername/$campaignSlug/players/$playerId'
      path: '/$playerId'
      fullPath: '/campaigns/$dmUsername/$campaignSlug/players/$playerId'
      preLoaderRoute: typeof AuthedCampaignsDmUsernameCampaignSlugPlayersPlayerIdRouteImport
      parentRoute: typeof AuthedCampaignsDmUsernameCampaignSlugPlayersRouteRoute
    }
  }
}

interface AuthedCampaignsDmUsernameCampaignSlugEditorRouteRouteChildren {
  AuthedCampaignsDmUsernameCampaignSlugEditorIndexRoute: typeof AuthedCampaignsDmUsernameCampaignSlugEditorIndexRoute
}

const AuthedCampaignsDmUsernameCampaignSlugEditorRouteRouteChildren: AuthedCampaignsDmUsernameCampaignSlugEditorRouteRouteChildren =
  {
    AuthedCampaignsDmUsernameCampaignSlugEditorIndexRoute:
      AuthedCampaignsDmUsernameCampaignSlugEditorIndexRoute,
  }

const AuthedCampaignsDmUsernameCampaignSlugEditorRouteRouteWithChildren =
  AuthedCampaignsDmUsernameCampaignSlugEditorRouteRoute._addFileChildren(
    AuthedCampaignsDmUsernameCampaignSlugEditorRouteRouteChildren,
  )

interface AuthedCampaignsDmUsernameCampaignSlugPlayersRouteRouteChildren {
  AuthedCampaignsDmUsernameCampaignSlugPlayersPlayerIdRoute: typeof AuthedCampaignsDmUsernameCampaignSlugPlayersPlayerIdRoute
  AuthedCampaignsDmUsernameCampaignSlugPlayersIndexRoute: typeof AuthedCampaignsDmUsernameCampaignSlugPlayersIndexRoute
}

const AuthedCampaignsDmUsernameCampaignSlugPlayersRouteRouteChildren: AuthedCampaignsDmUsernameCampaignSlugPlayersRouteRouteChildren =
  {
    AuthedCampaignsDmUsernameCampaignSlugPlayersPlayerIdRoute:
      AuthedCampaignsDmUsernameCampaignSlugPlayersPlayerIdRoute,
    AuthedCampaignsDmUsernameCampaignSlugPlayersIndexRoute:
      AuthedCampaignsDmUsernameCampaignSlugPlayersIndexRoute,
  }

const AuthedCampaignsDmUsernameCampaignSlugPlayersRouteRouteWithChildren =
  AuthedCampaignsDmUsernameCampaignSlugPlayersRouteRoute._addFileChildren(
    AuthedCampaignsDmUsernameCampaignSlugPlayersRouteRouteChildren,
  )

interface AuthedCampaignsDmUsernameCampaignSlugRouteRouteChildren {
  AuthedCampaignsDmUsernameCampaignSlugEditorRouteRoute: typeof AuthedCampaignsDmUsernameCampaignSlugEditorRouteRouteWithChildren
  AuthedCampaignsDmUsernameCampaignSlugPlayersRouteRoute: typeof AuthedCampaignsDmUsernameCampaignSlugPlayersRouteRouteWithChildren
  AuthedCampaignsDmUsernameCampaignSlugIndexRoute: typeof AuthedCampaignsDmUsernameCampaignSlugIndexRoute
  AuthedCampaignsDmUsernameCampaignSlugSettingsIndexRoute: typeof AuthedCampaignsDmUsernameCampaignSlugSettingsIndexRoute
}

const AuthedCampaignsDmUsernameCampaignSlugRouteRouteChildren: AuthedCampaignsDmUsernameCampaignSlugRouteRouteChildren =
  {
    AuthedCampaignsDmUsernameCampaignSlugEditorRouteRoute:
      AuthedCampaignsDmUsernameCampaignSlugEditorRouteRouteWithChildren,
    AuthedCampaignsDmUsernameCampaignSlugPlayersRouteRoute:
      AuthedCampaignsDmUsernameCampaignSlugPlayersRouteRouteWithChildren,
    AuthedCampaignsDmUsernameCampaignSlugIndexRoute:
      AuthedCampaignsDmUsernameCampaignSlugIndexRoute,
    AuthedCampaignsDmUsernameCampaignSlugSettingsIndexRoute:
      AuthedCampaignsDmUsernameCampaignSlugSettingsIndexRoute,
  }

const AuthedCampaignsDmUsernameCampaignSlugRouteRouteWithChildren =
  AuthedCampaignsDmUsernameCampaignSlugRouteRoute._addFileChildren(
    AuthedCampaignsDmUsernameCampaignSlugRouteRouteChildren,
  )

interface AuthedCampaignsRouteRouteChildren {
  AuthedCampaignsIndexRoute: typeof AuthedCampaignsIndexRoute
  AuthedCampaignsDmUsernameCampaignSlugRouteRoute: typeof AuthedCampaignsDmUsernameCampaignSlugRouteRouteWithChildren
}

const AuthedCampaignsRouteRouteChildren: AuthedCampaignsRouteRouteChildren = {
  AuthedCampaignsIndexRoute: AuthedCampaignsIndexRoute,
  AuthedCampaignsDmUsernameCampaignSlugRouteRoute:
    AuthedCampaignsDmUsernameCampaignSlugRouteRouteWithChildren,
}

const AuthedCampaignsRouteRouteWithChildren =
  AuthedCampaignsRouteRoute._addFileChildren(AuthedCampaignsRouteRouteChildren)

interface AuthedRouteRouteChildren {
  AuthedCampaignsRouteRoute: typeof AuthedCampaignsRouteRouteWithChildren
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedCampaignsRouteRoute: AuthedCampaignsRouteRouteWithChildren,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  AuthRedirectRouteRoute: AuthRedirectRouteRoute,
  SignInRouteRoute: SignInRouteRoute,
  SignUpRouteRoute: SignUpRouteRoute,
  JoinDmUsernameCampaignSlugIndexRoute: JoinDmUsernameCampaignSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
