/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteRouteImport } from './routes/sign-up/route'
import { Route as SignInRouteRouteImport } from './routes/sign-in/route'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedCampaignsRouteRouteImport } from './routes/_authed/campaigns/route'
import { Route as AuthedCampaignsIndexRouteImport } from './routes/_authed/campaigns/index'
import { Route as JoinDmUsernameCampaignSlugIndexRouteImport } from './routes/join.$dmUsername.$campaignSlug/index'
import { Route as AuthedCampaignsDmUsernameCampaignSlugRouteRouteImport } from './routes/_authed/campaigns/$dmUsername.$campaignSlug/route'
import { Route as AuthedCampaignsDmUsernameCampaignSlugIndexRouteImport } from './routes/_authed/campaigns/$dmUsername.$campaignSlug/index'
import { Route as AuthedCampaignsDmUsernameCampaignSlugPlayersRouteRouteImport } from './routes/_authed/campaigns/$dmUsername.$campaignSlug/players/route'
import { Route as AuthedCampaignsDmUsernameCampaignSlugNotesRouteRouteImport } from './routes/_authed/campaigns/$dmUsername.$campaignSlug/notes/route'
import { Route as AuthedCampaignsDmUsernameCampaignSlugSettingsIndexRouteImport } from './routes/_authed/campaigns/$dmUsername.$campaignSlug/settings/index'
import { Route as AuthedCampaignsDmUsernameCampaignSlugPlayersIndexRouteImport } from './routes/_authed/campaigns/$dmUsername.$campaignSlug/players/index'
import { Route as AuthedCampaignsDmUsernameCampaignSlugNotesIndexRouteImport } from './routes/_authed/campaigns/$dmUsername.$campaignSlug/notes/index'
import { Route as AuthedCampaignsDmUsernameCampaignSlugPlayersPlayerIdRouteImport } from './routes/_authed/campaigns/$dmUsername.$campaignSlug/players/$playerId'
import { Route as AuthedCampaignsDmUsernameCampaignSlugNotesNoteSlugRouteImport } from './routes/_authed/campaigns/$dmUsername.$campaignSlug/notes/$noteSlug'
import { Route as AuthedCampaignsDmUsernameCampaignSlugCategoriesCharactersRouteRouteImport } from './routes/_authed/campaigns/$dmUsername.$campaignSlug/categories/characters/route'
import { Route as AuthedCampaignsDmUsernameCampaignSlugCategoriesLocationsIndexRouteImport } from './routes/_authed/campaigns/$dmUsername.$campaignSlug/categories/locations/index'
import { Route as AuthedCampaignsDmUsernameCampaignSlugCategoriesCharactersIndexRouteImport } from './routes/_authed/campaigns/$dmUsername.$campaignSlug/categories/characters/index'
import { Route as AuthedCampaignsDmUsernameCampaignSlugCategoriesCategorySlugIndexRouteImport } from './routes/_authed/campaigns/$dmUsername.$campaignSlug/categories/$categorySlug/index'
import { Route as AuthedCampaignsDmUsernameCampaignSlugCategoriesLocationsRoutesRouteImport } from './routes/_authed/campaigns/$dmUsername.$campaignSlug/categories/locations/routes'
import { Route as AuthedCampaignsDmUsernameCampaignSlugCategoriesLocationsLocationIdRouteImport } from './routes/_authed/campaigns/$dmUsername.$campaignSlug/categories/locations/$locationId'
import { Route as AuthedCampaignsDmUsernameCampaignSlugCategoriesCharactersCharacterIdRouteImport } from './routes/_authed/campaigns/$dmUsername.$campaignSlug/categories/characters/$characterId'

const SignUpRouteRoute = SignUpRouteRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRouteRoute = SignInRouteRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedCampaignsRouteRoute = AuthedCampaignsRouteRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedCampaignsIndexRoute = AuthedCampaignsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedCampaignsRouteRoute,
} as any)
const JoinDmUsernameCampaignSlugIndexRoute =
  JoinDmUsernameCampaignSlugIndexRouteImport.update({
    id: '/join/$dmUsername/$campaignSlug/',
    path: '/join/$dmUsername/$campaignSlug/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthedCampaignsDmUsernameCampaignSlugRouteRoute =
  AuthedCampaignsDmUsernameCampaignSlugRouteRouteImport.update({
    id: '/$dmUsername/$campaignSlug',
    path: '/$dmUsername/$campaignSlug',
    getParentRoute: () => AuthedCampaignsRouteRoute,
  } as any)
const AuthedCampaignsDmUsernameCampaignSlugIndexRoute =
  AuthedCampaignsDmUsernameCampaignSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedCampaignsDmUsernameCampaignSlugRouteRoute,
  } as any)
const AuthedCampaignsDmUsernameCampaignSlugPlayersRouteRoute =
  AuthedCampaignsDmUsernameCampaignSlugPlayersRouteRouteImport.update({
    id: '/players',
    path: '/players',
    getParentRoute: () => AuthedCampaignsDmUsernameCampaignSlugRouteRoute,
  } as any)
const AuthedCampaignsDmUsernameCampaignSlugNotesRouteRoute =
  AuthedCampaignsDmUsernameCampaignSlugNotesRouteRouteImport.update({
    id: '/notes',
    path: '/notes',
    getParentRoute: () => AuthedCampaignsDmUsernameCampaignSlugRouteRoute,
  } as any)
const AuthedCampaignsDmUsernameCampaignSlugSettingsIndexRoute =
  AuthedCampaignsDmUsernameCampaignSlugSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthedCampaignsDmUsernameCampaignSlugRouteRoute,
  } as any)
const AuthedCampaignsDmUsernameCampaignSlugPlayersIndexRoute =
  AuthedCampaignsDmUsernameCampaignSlugPlayersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () =>
      AuthedCampaignsDmUsernameCampaignSlugPlayersRouteRoute,
  } as any)
const AuthedCampaignsDmUsernameCampaignSlugNotesIndexRoute =
  AuthedCampaignsDmUsernameCampaignSlugNotesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedCampaignsDmUsernameCampaignSlugNotesRouteRoute,
  } as any)
const AuthedCampaignsDmUsernameCampaignSlugPlayersPlayerIdRoute =
  AuthedCampaignsDmUsernameCampaignSlugPlayersPlayerIdRouteImport.update({
    id: '/$playerId',
    path: '/$playerId',
    getParentRoute: () =>
      AuthedCampaignsDmUsernameCampaignSlugPlayersRouteRoute,
  } as any)
const AuthedCampaignsDmUsernameCampaignSlugNotesNoteSlugRoute =
  AuthedCampaignsDmUsernameCampaignSlugNotesNoteSlugRouteImport.update({
    id: '/$noteSlug',
    path: '/$noteSlug',
    getParentRoute: () => AuthedCampaignsDmUsernameCampaignSlugNotesRouteRoute,
  } as any)
const AuthedCampaignsDmUsernameCampaignSlugCategoriesCharactersRouteRoute =
  AuthedCampaignsDmUsernameCampaignSlugCategoriesCharactersRouteRouteImport.update(
    {
      id: '/categories/characters',
      path: '/categories/characters',
      getParentRoute: () => AuthedCampaignsDmUsernameCampaignSlugRouteRoute,
    } as any,
  )
const AuthedCampaignsDmUsernameCampaignSlugCategoriesLocationsIndexRoute =
  AuthedCampaignsDmUsernameCampaignSlugCategoriesLocationsIndexRouteImport.update(
    {
      id: '/categories/locations/',
      path: '/categories/locations/',
      getParentRoute: () => AuthedCampaignsDmUsernameCampaignSlugRouteRoute,
    } as any,
  )
const AuthedCampaignsDmUsernameCampaignSlugCategoriesCharactersIndexRoute =
  AuthedCampaignsDmUsernameCampaignSlugCategoriesCharactersIndexRouteImport.update(
    {
      id: '/',
      path: '/',
      getParentRoute: () =>
        AuthedCampaignsDmUsernameCampaignSlugCategoriesCharactersRouteRoute,
    } as any,
  )
const AuthedCampaignsDmUsernameCampaignSlugCategoriesCategorySlugIndexRoute =
  AuthedCampaignsDmUsernameCampaignSlugCategoriesCategorySlugIndexRouteImport.update(
    {
      id: '/categories/$categorySlug/',
      path: '/categories/$categorySlug/',
      getParentRoute: () => AuthedCampaignsDmUsernameCampaignSlugRouteRoute,
    } as any,
  )
const AuthedCampaignsDmUsernameCampaignSlugCategoriesLocationsRoutesRoute =
  AuthedCampaignsDmUsernameCampaignSlugCategoriesLocationsRoutesRouteImport.update(
    {
      id: '/categories/locations/routes',
      path: '/categories/locations/routes',
      getParentRoute: () => AuthedCampaignsDmUsernameCampaignSlugRouteRoute,
    } as any,
  )
const AuthedCampaignsDmUsernameCampaignSlugCategoriesLocationsLocationIdRoute =
  AuthedCampaignsDmUsernameCampaignSlugCategoriesLocationsLocationIdRouteImport.update(
    {
      id: '/categories/locations/$locationId',
      path: '/categories/locations/$locationId',
      getParentRoute: () => AuthedCampaignsDmUsernameCampaignSlugRouteRoute,
    } as any,
  )
const AuthedCampaignsDmUsernameCampaignSlugCategoriesCharactersCharacterIdRoute =
  AuthedCampaignsDmUsernameCampaignSlugCategoriesCharactersCharacterIdRouteImport.update(
    {
      id: '/$characterId',
      path: '/$characterId',
      getParentRoute: () =>
        AuthedCampaignsDmUsernameCampaignSlugCategoriesCharactersRouteRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRouteRoute
  '/sign-up': typeof SignUpRouteRoute
  '/campaigns': typeof AuthedCampaignsRouteRouteWithChildren
  '/campaigns/': typeof AuthedCampaignsIndexRoute
  '/campaigns/$dmUsername/$campaignSlug': typeof AuthedCampaignsDmUsernameCampaignSlugRouteRouteWithChildren
  '/join/$dmUsername/$campaignSlug': typeof JoinDmUsernameCampaignSlugIndexRoute
  '/campaigns/$dmUsername/$campaignSlug/notes': typeof AuthedCampaignsDmUsernameCampaignSlugNotesRouteRouteWithChildren
  '/campaigns/$dmUsername/$campaignSlug/players': typeof AuthedCampaignsDmUsernameCampaignSlugPlayersRouteRouteWithChildren
  '/campaigns/$dmUsername/$campaignSlug/': typeof AuthedCampaignsDmUsernameCampaignSlugIndexRoute
  '/campaigns/$dmUsername/$campaignSlug/categories/characters': typeof AuthedCampaignsDmUsernameCampaignSlugCategoriesCharactersRouteRouteWithChildren
  '/campaigns/$dmUsername/$campaignSlug/notes/$noteSlug': typeof AuthedCampaignsDmUsernameCampaignSlugNotesNoteSlugRoute
  '/campaigns/$dmUsername/$campaignSlug/players/$playerId': typeof AuthedCampaignsDmUsernameCampaignSlugPlayersPlayerIdRoute
  '/campaigns/$dmUsername/$campaignSlug/notes/': typeof AuthedCampaignsDmUsernameCampaignSlugNotesIndexRoute
  '/campaigns/$dmUsername/$campaignSlug/players/': typeof AuthedCampaignsDmUsernameCampaignSlugPlayersIndexRoute
  '/campaigns/$dmUsername/$campaignSlug/settings': typeof AuthedCampaignsDmUsernameCampaignSlugSettingsIndexRoute
  '/campaigns/$dmUsername/$campaignSlug/categories/characters/$characterId': typeof AuthedCampaignsDmUsernameCampaignSlugCategoriesCharactersCharacterIdRoute
  '/campaigns/$dmUsername/$campaignSlug/categories/locations/$locationId': typeof AuthedCampaignsDmUsernameCampaignSlugCategoriesLocationsLocationIdRoute
  '/campaigns/$dmUsername/$campaignSlug/categories/locations/routes': typeof AuthedCampaignsDmUsernameCampaignSlugCategoriesLocationsRoutesRoute
  '/campaigns/$dmUsername/$campaignSlug/categories/$categorySlug': typeof AuthedCampaignsDmUsernameCampaignSlugCategoriesCategorySlugIndexRoute
  '/campaigns/$dmUsername/$campaignSlug/categories/characters/': typeof AuthedCampaignsDmUsernameCampaignSlugCategoriesCharactersIndexRoute
  '/campaigns/$dmUsername/$campaignSlug/categories/locations': typeof AuthedCampaignsDmUsernameCampaignSlugCategoriesLocationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRouteRoute
  '/sign-up': typeof SignUpRouteRoute
  '/campaigns': typeof AuthedCampaignsIndexRoute
  '/join/$dmUsername/$campaignSlug': typeof JoinDmUsernameCampaignSlugIndexRoute
  '/campaigns/$dmUsername/$campaignSlug': typeof AuthedCampaignsDmUsernameCampaignSlugIndexRoute
  '/campaigns/$dmUsername/$campaignSlug/notes/$noteSlug': typeof AuthedCampaignsDmUsernameCampaignSlugNotesNoteSlugRoute
  '/campaigns/$dmUsername/$campaignSlug/players/$playerId': typeof AuthedCampaignsDmUsernameCampaignSlugPlayersPlayerIdRoute
  '/campaigns/$dmUsername/$campaignSlug/notes': typeof AuthedCampaignsDmUsernameCampaignSlugNotesIndexRoute
  '/campaigns/$dmUsername/$campaignSlug/players': typeof AuthedCampaignsDmUsernameCampaignSlugPlayersIndexRoute
  '/campaigns/$dmUsername/$campaignSlug/settings': typeof AuthedCampaignsDmUsernameCampaignSlugSettingsIndexRoute
  '/campaigns/$dmUsername/$campaignSlug/categories/characters/$characterId': typeof AuthedCampaignsDmUsernameCampaignSlugCategoriesCharactersCharacterIdRoute
  '/campaigns/$dmUsername/$campaignSlug/categories/locations/$locationId': typeof AuthedCampaignsDmUsernameCampaignSlugCategoriesLocationsLocationIdRoute
  '/campaigns/$dmUsername/$campaignSlug/categories/locations/routes': typeof AuthedCampaignsDmUsernameCampaignSlugCategoriesLocationsRoutesRoute
  '/campaigns/$dmUsername/$campaignSlug/categories/$categorySlug': typeof AuthedCampaignsDmUsernameCampaignSlugCategoriesCategorySlugIndexRoute
  '/campaigns/$dmUsername/$campaignSlug/categories/characters': typeof AuthedCampaignsDmUsernameCampaignSlugCategoriesCharactersIndexRoute
  '/campaigns/$dmUsername/$campaignSlug/categories/locations': typeof AuthedCampaignsDmUsernameCampaignSlugCategoriesLocationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/sign-in': typeof SignInRouteRoute
  '/sign-up': typeof SignUpRouteRoute
  '/_authed/campaigns': typeof AuthedCampaignsRouteRouteWithChildren
  '/_authed/campaigns/': typeof AuthedCampaignsIndexRoute
  '/_authed/campaigns/$dmUsername/$campaignSlug': typeof AuthedCampaignsDmUsernameCampaignSlugRouteRouteWithChildren
  '/join/$dmUsername/$campaignSlug/': typeof JoinDmUsernameCampaignSlugIndexRoute
  '/_authed/campaigns/$dmUsername/$campaignSlug/notes': typeof AuthedCampaignsDmUsernameCampaignSlugNotesRouteRouteWithChildren
  '/_authed/campaigns/$dmUsername/$campaignSlug/players': typeof AuthedCampaignsDmUsernameCampaignSlugPlayersRouteRouteWithChildren
  '/_authed/campaigns/$dmUsername/$campaignSlug/': typeof AuthedCampaignsDmUsernameCampaignSlugIndexRoute
  '/_authed/campaigns/$dmUsername/$campaignSlug/categories/characters': typeof AuthedCampaignsDmUsernameCampaignSlugCategoriesCharactersRouteRouteWithChildren
  '/_authed/campaigns/$dmUsername/$campaignSlug/notes/$noteSlug': typeof AuthedCampaignsDmUsernameCampaignSlugNotesNoteSlugRoute
  '/_authed/campaigns/$dmUsername/$campaignSlug/players/$playerId': typeof AuthedCampaignsDmUsernameCampaignSlugPlayersPlayerIdRoute
  '/_authed/campaigns/$dmUsername/$campaignSlug/notes/': typeof AuthedCampaignsDmUsernameCampaignSlugNotesIndexRoute
  '/_authed/campaigns/$dmUsername/$campaignSlug/players/': typeof AuthedCampaignsDmUsernameCampaignSlugPlayersIndexRoute
  '/_authed/campaigns/$dmUsername/$campaignSlug/settings/': typeof AuthedCampaignsDmUsernameCampaignSlugSettingsIndexRoute
  '/_authed/campaigns/$dmUsername/$campaignSlug/categories/characters/$characterId': typeof AuthedCampaignsDmUsernameCampaignSlugCategoriesCharactersCharacterIdRoute
  '/_authed/campaigns/$dmUsername/$campaignSlug/categories/locations/$locationId': typeof AuthedCampaignsDmUsernameCampaignSlugCategoriesLocationsLocationIdRoute
  '/_authed/campaigns/$dmUsername/$campaignSlug/categories/locations/routes': typeof AuthedCampaignsDmUsernameCampaignSlugCategoriesLocationsRoutesRoute
  '/_authed/campaigns/$dmUsername/$campaignSlug/categories/$categorySlug/': typeof AuthedCampaignsDmUsernameCampaignSlugCategoriesCategorySlugIndexRoute
  '/_authed/campaigns/$dmUsername/$campaignSlug/categories/characters/': typeof AuthedCampaignsDmUsernameCampaignSlugCategoriesCharactersIndexRoute
  '/_authed/campaigns/$dmUsername/$campaignSlug/categories/locations/': typeof AuthedCampaignsDmUsernameCampaignSlugCategoriesLocationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/campaigns'
    | '/campaigns/'
    | '/campaigns/$dmUsername/$campaignSlug'
    | '/join/$dmUsername/$campaignSlug'
    | '/campaigns/$dmUsername/$campaignSlug/notes'
    | '/campaigns/$dmUsername/$campaignSlug/players'
    | '/campaigns/$dmUsername/$campaignSlug/'
    | '/campaigns/$dmUsername/$campaignSlug/categories/characters'
    | '/campaigns/$dmUsername/$campaignSlug/notes/$noteSlug'
    | '/campaigns/$dmUsername/$campaignSlug/players/$playerId'
    | '/campaigns/$dmUsername/$campaignSlug/notes/'
    | '/campaigns/$dmUsername/$campaignSlug/players/'
    | '/campaigns/$dmUsername/$campaignSlug/settings'
    | '/campaigns/$dmUsername/$campaignSlug/categories/characters/$characterId'
    | '/campaigns/$dmUsername/$campaignSlug/categories/locations/$locationId'
    | '/campaigns/$dmUsername/$campaignSlug/categories/locations/routes'
    | '/campaigns/$dmUsername/$campaignSlug/categories/$categorySlug'
    | '/campaigns/$dmUsername/$campaignSlug/categories/characters/'
    | '/campaigns/$dmUsername/$campaignSlug/categories/locations'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/campaigns'
    | '/join/$dmUsername/$campaignSlug'
    | '/campaigns/$dmUsername/$campaignSlug'
    | '/campaigns/$dmUsername/$campaignSlug/notes/$noteSlug'
    | '/campaigns/$dmUsername/$campaignSlug/players/$playerId'
    | '/campaigns/$dmUsername/$campaignSlug/notes'
    | '/campaigns/$dmUsername/$campaignSlug/players'
    | '/campaigns/$dmUsername/$campaignSlug/settings'
    | '/campaigns/$dmUsername/$campaignSlug/categories/characters/$characterId'
    | '/campaigns/$dmUsername/$campaignSlug/categories/locations/$locationId'
    | '/campaigns/$dmUsername/$campaignSlug/categories/locations/routes'
    | '/campaigns/$dmUsername/$campaignSlug/categories/$categorySlug'
    | '/campaigns/$dmUsername/$campaignSlug/categories/characters'
    | '/campaigns/$dmUsername/$campaignSlug/categories/locations'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/sign-in'
    | '/sign-up'
    | '/_authed/campaigns'
    | '/_authed/campaigns/'
    | '/_authed/campaigns/$dmUsername/$campaignSlug'
    | '/join/$dmUsername/$campaignSlug/'
    | '/_authed/campaigns/$dmUsername/$campaignSlug/notes'
    | '/_authed/campaigns/$dmUsername/$campaignSlug/players'
    | '/_authed/campaigns/$dmUsername/$campaignSlug/'
    | '/_authed/campaigns/$dmUsername/$campaignSlug/categories/characters'
    | '/_authed/campaigns/$dmUsername/$campaignSlug/notes/$noteSlug'
    | '/_authed/campaigns/$dmUsername/$campaignSlug/players/$playerId'
    | '/_authed/campaigns/$dmUsername/$campaignSlug/notes/'
    | '/_authed/campaigns/$dmUsername/$campaignSlug/players/'
    | '/_authed/campaigns/$dmUsername/$campaignSlug/settings/'
    | '/_authed/campaigns/$dmUsername/$campaignSlug/categories/characters/$characterId'
    | '/_authed/campaigns/$dmUsername/$campaignSlug/categories/locations/$locationId'
    | '/_authed/campaigns/$dmUsername/$campaignSlug/categories/locations/routes'
    | '/_authed/campaigns/$dmUsername/$campaignSlug/categories/$categorySlug/'
    | '/_authed/campaigns/$dmUsername/$campaignSlug/categories/characters/'
    | '/_authed/campaigns/$dmUsername/$campaignSlug/categories/locations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  SignInRouteRoute: typeof SignInRouteRoute
  SignUpRouteRoute: typeof SignUpRouteRoute
  JoinDmUsernameCampaignSlugIndexRoute: typeof JoinDmUsernameCampaignSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/campaigns': {
      id: '/_authed/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof AuthedCampaignsRouteRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/campaigns/': {
      id: '/_authed/campaigns/'
      path: '/'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof AuthedCampaignsIndexRouteImport
      parentRoute: typeof AuthedCampaignsRouteRoute
    }
    '/join/$dmUsername/$campaignSlug/': {
      id: '/join/$dmUsername/$campaignSlug/'
      path: '/join/$dmUsername/$campaignSlug'
      fullPath: '/join/$dmUsername/$campaignSlug'
      preLoaderRoute: typeof JoinDmUsernameCampaignSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/campaigns/$dmUsername/$campaignSlug': {
      id: '/_authed/campaigns/$dmUsername/$campaignSlug'
      path: '/$dmUsername/$campaignSlug'
      fullPath: '/campaigns/$dmUsername/$campaignSlug'
      preLoaderRoute: typeof AuthedCampaignsDmUsernameCampaignSlugRouteRouteImport
      parentRoute: typeof AuthedCampaignsRouteRoute
    }
    '/_authed/campaigns/$dmUsername/$campaignSlug/': {
      id: '/_authed/campaigns/$dmUsername/$campaignSlug/'
      path: '/'
      fullPath: '/campaigns/$dmUsername/$campaignSlug/'
      preLoaderRoute: typeof AuthedCampaignsDmUsernameCampaignSlugIndexRouteImport
      parentRoute: typeof AuthedCampaignsDmUsernameCampaignSlugRouteRoute
    }
    '/_authed/campaigns/$dmUsername/$campaignSlug/players': {
      id: '/_authed/campaigns/$dmUsername/$campaignSlug/players'
      path: '/players'
      fullPath: '/campaigns/$dmUsername/$campaignSlug/players'
      preLoaderRoute: typeof AuthedCampaignsDmUsernameCampaignSlugPlayersRouteRouteImport
      parentRoute: typeof AuthedCampaignsDmUsernameCampaignSlugRouteRoute
    }
    '/_authed/campaigns/$dmUsername/$campaignSlug/notes': {
      id: '/_authed/campaigns/$dmUsername/$campaignSlug/notes'
      path: '/notes'
      fullPath: '/campaigns/$dmUsername/$campaignSlug/notes'
      preLoaderRoute: typeof AuthedCampaignsDmUsernameCampaignSlugNotesRouteRouteImport
      parentRoute: typeof AuthedCampaignsDmUsernameCampaignSlugRouteRoute
    }
    '/_authed/campaigns/$dmUsername/$campaignSlug/settings/': {
      id: '/_authed/campaigns/$dmUsername/$campaignSlug/settings/'
      path: '/settings'
      fullPath: '/campaigns/$dmUsername/$campaignSlug/settings'
      preLoaderRoute: typeof AuthedCampaignsDmUsernameCampaignSlugSettingsIndexRouteImport
      parentRoute: typeof AuthedCampaignsDmUsernameCampaignSlugRouteRoute
    }
    '/_authed/campaigns/$dmUsername/$campaignSlug/players/': {
      id: '/_authed/campaigns/$dmUsername/$campaignSlug/players/'
      path: '/'
      fullPath: '/campaigns/$dmUsername/$campaignSlug/players/'
      preLoaderRoute: typeof AuthedCampaignsDmUsernameCampaignSlugPlayersIndexRouteImport
      parentRoute: typeof AuthedCampaignsDmUsernameCampaignSlugPlayersRouteRoute
    }
    '/_authed/campaigns/$dmUsername/$campaignSlug/notes/': {
      id: '/_authed/campaigns/$dmUsername/$campaignSlug/notes/'
      path: '/'
      fullPath: '/campaigns/$dmUsername/$campaignSlug/notes/'
      preLoaderRoute: typeof AuthedCampaignsDmUsernameCampaignSlugNotesIndexRouteImport
      parentRoute: typeof AuthedCampaignsDmUsernameCampaignSlugNotesRouteRoute
    }
    '/_authed/campaigns/$dmUsername/$campaignSlug/players/$playerId': {
      id: '/_authed/campaigns/$dmUsername/$campaignSlug/players/$playerId'
      path: '/$playerId'
      fullPath: '/campaigns/$dmUsername/$campaignSlug/players/$playerId'
      preLoaderRoute: typeof AuthedCampaignsDmUsernameCampaignSlugPlayersPlayerIdRouteImport
      parentRoute: typeof AuthedCampaignsDmUsernameCampaignSlugPlayersRouteRoute
    }
    '/_authed/campaigns/$dmUsername/$campaignSlug/notes/$noteSlug': {
      id: '/_authed/campaigns/$dmUsername/$campaignSlug/notes/$noteSlug'
      path: '/$noteSlug'
      fullPath: '/campaigns/$dmUsername/$campaignSlug/notes/$noteSlug'
      preLoaderRoute: typeof AuthedCampaignsDmUsernameCampaignSlugNotesNoteSlugRouteImport
      parentRoute: typeof AuthedCampaignsDmUsernameCampaignSlugNotesRouteRoute
    }
    '/_authed/campaigns/$dmUsername/$campaignSlug/categories/characters': {
      id: '/_authed/campaigns/$dmUsername/$campaignSlug/categories/characters'
      path: '/categories/characters'
      fullPath: '/campaigns/$dmUsername/$campaignSlug/categories/characters'
      preLoaderRoute: typeof AuthedCampaignsDmUsernameCampaignSlugCategoriesCharactersRouteRouteImport
      parentRoute: typeof AuthedCampaignsDmUsernameCampaignSlugRouteRoute
    }
    '/_authed/campaigns/$dmUsername/$campaignSlug/categories/locations/': {
      id: '/_authed/campaigns/$dmUsername/$campaignSlug/categories/locations/'
      path: '/categories/locations'
      fullPath: '/campaigns/$dmUsername/$campaignSlug/categories/locations'
      preLoaderRoute: typeof AuthedCampaignsDmUsernameCampaignSlugCategoriesLocationsIndexRouteImport
      parentRoute: typeof AuthedCampaignsDmUsernameCampaignSlugRouteRoute
    }
    '/_authed/campaigns/$dmUsername/$campaignSlug/categories/characters/': {
      id: '/_authed/campaigns/$dmUsername/$campaignSlug/categories/characters/'
      path: '/'
      fullPath: '/campaigns/$dmUsername/$campaignSlug/categories/characters/'
      preLoaderRoute: typeof AuthedCampaignsDmUsernameCampaignSlugCategoriesCharactersIndexRouteImport
      parentRoute: typeof AuthedCampaignsDmUsernameCampaignSlugCategoriesCharactersRouteRoute
    }
    '/_authed/campaigns/$dmUsername/$campaignSlug/categories/$categorySlug/': {
      id: '/_authed/campaigns/$dmUsername/$campaignSlug/categories/$categorySlug/'
      path: '/categories/$categorySlug'
      fullPath: '/campaigns/$dmUsername/$campaignSlug/categories/$categorySlug'
      preLoaderRoute: typeof AuthedCampaignsDmUsernameCampaignSlugCategoriesCategorySlugIndexRouteImport
      parentRoute: typeof AuthedCampaignsDmUsernameCampaignSlugRouteRoute
    }
    '/_authed/campaigns/$dmUsername/$campaignSlug/categories/locations/routes': {
      id: '/_authed/campaigns/$dmUsername/$campaignSlug/categories/locations/routes'
      path: '/categories/locations/routes'
      fullPath: '/campaigns/$dmUsername/$campaignSlug/categories/locations/routes'
      preLoaderRoute: typeof AuthedCampaignsDmUsernameCampaignSlugCategoriesLocationsRoutesRouteImport
      parentRoute: typeof AuthedCampaignsDmUsernameCampaignSlugRouteRoute
    }
    '/_authed/campaigns/$dmUsername/$campaignSlug/categories/locations/$locationId': {
      id: '/_authed/campaigns/$dmUsername/$campaignSlug/categories/locations/$locationId'
      path: '/categories/locations/$locationId'
      fullPath: '/campaigns/$dmUsername/$campaignSlug/categories/locations/$locationId'
      preLoaderRoute: typeof AuthedCampaignsDmUsernameCampaignSlugCategoriesLocationsLocationIdRouteImport
      parentRoute: typeof AuthedCampaignsDmUsernameCampaignSlugRouteRoute
    }
    '/_authed/campaigns/$dmUsername/$campaignSlug/categories/characters/$characterId': {
      id: '/_authed/campaigns/$dmUsername/$campaignSlug/categories/characters/$characterId'
      path: '/$characterId'
      fullPath: '/campaigns/$dmUsername/$campaignSlug/categories/characters/$characterId'
      preLoaderRoute: typeof AuthedCampaignsDmUsernameCampaignSlugCategoriesCharactersCharacterIdRouteImport
      parentRoute: typeof AuthedCampaignsDmUsernameCampaignSlugCategoriesCharactersRouteRoute
    }
  }
}

interface AuthedCampaignsDmUsernameCampaignSlugNotesRouteRouteChildren {
  AuthedCampaignsDmUsernameCampaignSlugNotesNoteSlugRoute: typeof AuthedCampaignsDmUsernameCampaignSlugNotesNoteSlugRoute
  AuthedCampaignsDmUsernameCampaignSlugNotesIndexRoute: typeof AuthedCampaignsDmUsernameCampaignSlugNotesIndexRoute
}

const AuthedCampaignsDmUsernameCampaignSlugNotesRouteRouteChildren: AuthedCampaignsDmUsernameCampaignSlugNotesRouteRouteChildren =
  {
    AuthedCampaignsDmUsernameCampaignSlugNotesNoteSlugRoute:
      AuthedCampaignsDmUsernameCampaignSlugNotesNoteSlugRoute,
    AuthedCampaignsDmUsernameCampaignSlugNotesIndexRoute:
      AuthedCampaignsDmUsernameCampaignSlugNotesIndexRoute,
  }

const AuthedCampaignsDmUsernameCampaignSlugNotesRouteRouteWithChildren =
  AuthedCampaignsDmUsernameCampaignSlugNotesRouteRoute._addFileChildren(
    AuthedCampaignsDmUsernameCampaignSlugNotesRouteRouteChildren,
  )

interface AuthedCampaignsDmUsernameCampaignSlugPlayersRouteRouteChildren {
  AuthedCampaignsDmUsernameCampaignSlugPlayersPlayerIdRoute: typeof AuthedCampaignsDmUsernameCampaignSlugPlayersPlayerIdRoute
  AuthedCampaignsDmUsernameCampaignSlugPlayersIndexRoute: typeof AuthedCampaignsDmUsernameCampaignSlugPlayersIndexRoute
}

const AuthedCampaignsDmUsernameCampaignSlugPlayersRouteRouteChildren: AuthedCampaignsDmUsernameCampaignSlugPlayersRouteRouteChildren =
  {
    AuthedCampaignsDmUsernameCampaignSlugPlayersPlayerIdRoute:
      AuthedCampaignsDmUsernameCampaignSlugPlayersPlayerIdRoute,
    AuthedCampaignsDmUsernameCampaignSlugPlayersIndexRoute:
      AuthedCampaignsDmUsernameCampaignSlugPlayersIndexRoute,
  }

const AuthedCampaignsDmUsernameCampaignSlugPlayersRouteRouteWithChildren =
  AuthedCampaignsDmUsernameCampaignSlugPlayersRouteRoute._addFileChildren(
    AuthedCampaignsDmUsernameCampaignSlugPlayersRouteRouteChildren,
  )

interface AuthedCampaignsDmUsernameCampaignSlugCategoriesCharactersRouteRouteChildren {
  AuthedCampaignsDmUsernameCampaignSlugCategoriesCharactersCharacterIdRoute: typeof AuthedCampaignsDmUsernameCampaignSlugCategoriesCharactersCharacterIdRoute
  AuthedCampaignsDmUsernameCampaignSlugCategoriesCharactersIndexRoute: typeof AuthedCampaignsDmUsernameCampaignSlugCategoriesCharactersIndexRoute
}

const AuthedCampaignsDmUsernameCampaignSlugCategoriesCharactersRouteRouteChildren: AuthedCampaignsDmUsernameCampaignSlugCategoriesCharactersRouteRouteChildren =
  {
    AuthedCampaignsDmUsernameCampaignSlugCategoriesCharactersCharacterIdRoute:
      AuthedCampaignsDmUsernameCampaignSlugCategoriesCharactersCharacterIdRoute,
    AuthedCampaignsDmUsernameCampaignSlugCategoriesCharactersIndexRoute:
      AuthedCampaignsDmUsernameCampaignSlugCategoriesCharactersIndexRoute,
  }

const AuthedCampaignsDmUsernameCampaignSlugCategoriesCharactersRouteRouteWithChildren =
  AuthedCampaignsDmUsernameCampaignSlugCategoriesCharactersRouteRoute._addFileChildren(
    AuthedCampaignsDmUsernameCampaignSlugCategoriesCharactersRouteRouteChildren,
  )

interface AuthedCampaignsDmUsernameCampaignSlugRouteRouteChildren {
  AuthedCampaignsDmUsernameCampaignSlugNotesRouteRoute: typeof AuthedCampaignsDmUsernameCampaignSlugNotesRouteRouteWithChildren
  AuthedCampaignsDmUsernameCampaignSlugPlayersRouteRoute: typeof AuthedCampaignsDmUsernameCampaignSlugPlayersRouteRouteWithChildren
  AuthedCampaignsDmUsernameCampaignSlugIndexRoute: typeof AuthedCampaignsDmUsernameCampaignSlugIndexRoute
  AuthedCampaignsDmUsernameCampaignSlugCategoriesCharactersRouteRoute: typeof AuthedCampaignsDmUsernameCampaignSlugCategoriesCharactersRouteRouteWithChildren
  AuthedCampaignsDmUsernameCampaignSlugSettingsIndexRoute: typeof AuthedCampaignsDmUsernameCampaignSlugSettingsIndexRoute
  AuthedCampaignsDmUsernameCampaignSlugCategoriesLocationsLocationIdRoute: typeof AuthedCampaignsDmUsernameCampaignSlugCategoriesLocationsLocationIdRoute
  AuthedCampaignsDmUsernameCampaignSlugCategoriesLocationsRoutesRoute: typeof AuthedCampaignsDmUsernameCampaignSlugCategoriesLocationsRoutesRoute
  AuthedCampaignsDmUsernameCampaignSlugCategoriesCategorySlugIndexRoute: typeof AuthedCampaignsDmUsernameCampaignSlugCategoriesCategorySlugIndexRoute
  AuthedCampaignsDmUsernameCampaignSlugCategoriesLocationsIndexRoute: typeof AuthedCampaignsDmUsernameCampaignSlugCategoriesLocationsIndexRoute
}

const AuthedCampaignsDmUsernameCampaignSlugRouteRouteChildren: AuthedCampaignsDmUsernameCampaignSlugRouteRouteChildren =
  {
    AuthedCampaignsDmUsernameCampaignSlugNotesRouteRoute:
      AuthedCampaignsDmUsernameCampaignSlugNotesRouteRouteWithChildren,
    AuthedCampaignsDmUsernameCampaignSlugPlayersRouteRoute:
      AuthedCampaignsDmUsernameCampaignSlugPlayersRouteRouteWithChildren,
    AuthedCampaignsDmUsernameCampaignSlugIndexRoute:
      AuthedCampaignsDmUsernameCampaignSlugIndexRoute,
    AuthedCampaignsDmUsernameCampaignSlugCategoriesCharactersRouteRoute:
      AuthedCampaignsDmUsernameCampaignSlugCategoriesCharactersRouteRouteWithChildren,
    AuthedCampaignsDmUsernameCampaignSlugSettingsIndexRoute:
      AuthedCampaignsDmUsernameCampaignSlugSettingsIndexRoute,
    AuthedCampaignsDmUsernameCampaignSlugCategoriesLocationsLocationIdRoute:
      AuthedCampaignsDmUsernameCampaignSlugCategoriesLocationsLocationIdRoute,
    AuthedCampaignsDmUsernameCampaignSlugCategoriesLocationsRoutesRoute:
      AuthedCampaignsDmUsernameCampaignSlugCategoriesLocationsRoutesRoute,
    AuthedCampaignsDmUsernameCampaignSlugCategoriesCategorySlugIndexRoute:
      AuthedCampaignsDmUsernameCampaignSlugCategoriesCategorySlugIndexRoute,
    AuthedCampaignsDmUsernameCampaignSlugCategoriesLocationsIndexRoute:
      AuthedCampaignsDmUsernameCampaignSlugCategoriesLocationsIndexRoute,
  }

const AuthedCampaignsDmUsernameCampaignSlugRouteRouteWithChildren =
  AuthedCampaignsDmUsernameCampaignSlugRouteRoute._addFileChildren(
    AuthedCampaignsDmUsernameCampaignSlugRouteRouteChildren,
  )

interface AuthedCampaignsRouteRouteChildren {
  AuthedCampaignsIndexRoute: typeof AuthedCampaignsIndexRoute
  AuthedCampaignsDmUsernameCampaignSlugRouteRoute: typeof AuthedCampaignsDmUsernameCampaignSlugRouteRouteWithChildren
}

const AuthedCampaignsRouteRouteChildren: AuthedCampaignsRouteRouteChildren = {
  AuthedCampaignsIndexRoute: AuthedCampaignsIndexRoute,
  AuthedCampaignsDmUsernameCampaignSlugRouteRoute:
    AuthedCampaignsDmUsernameCampaignSlugRouteRouteWithChildren,
}

const AuthedCampaignsRouteRouteWithChildren =
  AuthedCampaignsRouteRoute._addFileChildren(AuthedCampaignsRouteRouteChildren)

interface AuthedRouteRouteChildren {
  AuthedCampaignsRouteRoute: typeof AuthedCampaignsRouteRouteWithChildren
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedCampaignsRouteRoute: AuthedCampaignsRouteRouteWithChildren,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  SignInRouteRoute: SignInRouteRoute,
  SignUpRouteRoute: SignUpRouteRoute,
  JoinDmUsernameCampaignSlugIndexRoute: JoinDmUsernameCampaignSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
